=== Fausti1971/JXG/bin/xsd/old/module.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- xs: erforderlich, da "byteType" bereits anderweitig belegt ist -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xgns="example.org" elementFormDefault="qualified">
	<xs:element name="map">
		<xs:complexType>
			<xs:sequence>
				<xs:element name = "module" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name = "name" type = "xs:string"/>
							<xs:element name = "address" type = "address" minOccurs="0"/>
							<xs:element name = "bulk" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name = "address" type = "address"/>
										<xs:element name = "size" type = "xs:nonNegativeInteger"/>
										<xs:element name = "opcode" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="address" type="address"/>
													<xs:element name="byteCount" type="xs:nonNegativeInteger" minOccurs="0"/>
													<xs:element name="byteType" type="byteType" minOccurs="0"/>
													<xs:element name="valueClass" type="valueClass" minOccurs="0"/>
												</xs:sequence>
											<xs:attribute name="ID" use="required" type="xs:ID"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					<xs:attribute name="ID" use="required" type="module"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="byteType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MIDIBYTE"/>
			<xs:enumeration value="NIBBLE"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="valueClass">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Integer"/>
			<xs:enumeration value="String"/>
			<xs:enumeration value="Image"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="module">
		<xs:restriction base="xs:NCName">
			<xs:enumeration value="system"/>
			<xs:enumeration value="info"/>
			<xs:enumeration value="sysfx"/>
			<xs:enumeration value="syseq"/>
			<xs:enumeration value="insfx"/>
			<xs:enumeration value="display"/>
			<xs:enumeration value="multipart"/>
			<xs:enumeration value="adpart"/>
			<xs:enumeration value="drumset"/>
			<xs:enumeration value="plugin"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="address">
		<xs:all>
			<xs:element name="hi" type="xs:nonNegativeInteger" minOccurs="0"/>
			<xs:element name="mid" type="xs:nonNegativeInteger" minOccurs="0"/>
			<xs:element name="lo" type="xs:nonNegativeInteger" minOccurs="0"/>
		</xs:all>
	</xs:complexType>
</xs:schema>

=== Fausti1971/JXG/rsc/XG/module.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--name (ID) und address obligatorisch; alle Werte dezimal; bei fehlendem (optionalem) ID wird Defaultwert benutzt:
	byteCount = 1
	byteType = MIDIBYTE
	valueClass = Integer
-->
<map xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../xsd/module.xsd">
	<module ID = "system">
		<name>Master</name>
		<address>
			<hi>0</hi>
			<mid>0</mid>
		</address>
		<bulk>
			<address>
				<hi>0</hi>
				<mid>0</mid>
			</address>
			<size>7</size>
			<opcode ID = "master_tune">
				<address>
					<lo>0</lo>
				</address>
				<byteCount>4</byteCount>
				<byteType>NIBBLE</byteType>
				<valueClass>Integer</valueClass>
			</opcode>
			<opcode ID = "master_volume">
				<address>
					<lo>4</lo>
				</address>
			</opcode>
			<opcode ID = "master_attenuator">
				<address>
					<lo>5</lo>
				</address>
			</opcode>
			<opcode ID = "master_transpose">
				<address>
					<lo>6</lo>
				</address>
			</opcode>
			<opcode ID = "master_reset_drumset">
				<address>
					<lo>125</lo>
				</address>
			</opcode>
			<opcode ID = "master_xg_on">
				<address>
					<lo>126</lo>
				</address>
			</opcode>
			<opcode ID = "master_reset_all">
				<address>
					<lo>127</lo>
				</address>
			</opcode>
		</bulk>
	</module>
	<module ID = "info">
		<name>System Information</name>
		<address>
			<hi>1</hi>
			<mid>0</mid>
		</address>
		<bulk>
			<address>
				<hi>1</hi>
				<mid>0</mid>
			</address>
			<size>16</size>
			<opcode ID = "info_name">
				<address>
					<lo>0</lo>
				</address>
				<byteCount>13</byteCount>
				<byteType>MIDIBYTE</byteType>
				<valueClass>String</valueClass>
			</opcode>
			<opcode ID = "info_xg_level1">
				<address>
					<lo>14</lo>
				</address>
			</opcode>
			<opcode ID = "info_xg_level2">
				<address>
					<lo>15</lo>
				</address>
			</opcode>
		</bulk>
	</module>
	<module ID = "sysfx">
		<name>System Effect</name>
		<address>
			<hi>2</hi>
			<mid>1</mid>
		</address>
		<bulk>
			<address>
				<hi>2</hi>
				<mid>1</mid>
			</address>
			<size>14</size>
			<opcode ID = "reverb_type">
				<address>
					<lo>0</lo>
				</address>
				<byteCount>2</byteCount>
				<byteType>MIDIBYTE</byteType>
				<valueClass>Integer</valueClass>
			</opcode>
			<opcode ID = "reverb_1">
				<address>
					<lo>2</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_2">
				<address>
					<lo>3</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_3">
				<address>
					<lo>4</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_4">
				<address>
					<lo>5</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_5">
				<address>
					<lo>6</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_6">
				<address>
					<lo>7</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_7">
				<address>
					<lo>8</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_8">
				<address>
					<lo>9</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_9">
				<address>
					<lo>10</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_10">
				<address>
					<lo>11</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_return">
				<address>
					<lo>12</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_panorama">
				<address>
					<lo>13</lo>
				</address>
			</opcode>
		</bulk>
		<bulk>
			<address>
				<hi>2</hi>
				<mid>1</mid>
			</address>
			<size>6</size>
			<opcode ID = "reverb_11">
				<address>
					<lo>16</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_12">
				<address>
					<lo>17</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_13">
				<address>
					<lo>18</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_14">
				<address>
					<lo>19</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_15">
				<address>
					<lo>20</lo>
				</address>
			</opcode>
			<opcode ID = "reverb_16">
				<address>
					<lo>21</lo>
				</address>
			</opcode>
		</bulk>
		<bulk>
			<address>
				<hi>2</hi>
				<mid>1</mid>
			</address>
			<size>15</size>
			<opcode ID = "chorus_type">
				<address>
					<lo>32</lo>
				</address>
				<byteCount>2</byteCount>
				<byteType>MIDIBYTE</byteType>
				<valueClass>Integer</valueClass>
			</opcode>
			<opcode ID = "chorus_1">
				<address>
					<lo>34</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_2">
				<address>
					<lo>35</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_3">
				<address>
					<lo>36</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_4">
				<address>
					<lo>37</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_5">
				<address>
					<lo>38</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_6">
				<address>
					<lo>39</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_7">
				<address>
					<lo>40</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_8">
				<address>
					<lo>41</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_9">
				<address>
					<lo>42</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_10">
				<address>
					<lo>43</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_return">
				<address>
					<lo>44</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_panorama">
				<address>
					<lo>45</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_to_reverb">
				<address>
					<lo>46</lo>
				</address>
			</opcode>
		</bulk>
		<bulk>
			<address>
				<hi>2</hi>
				<mid>1</mid>
			</address>
			<size>6</size>
			<opcode ID = "chorus_11">
				<address>
					<lo>48</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_12">
				<address>
					<lo>49</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_13">
				<address>
					<lo>50</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_14">
				<address>
					<lo>51</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_15">
				<address>
					<lo>52</lo>
				</address>
			</opcode>
			<opcode ID = "chorus_16">
				<address>
					<lo>53</lo>
				</address>
			</opcode>
		</bulk>
		<bulk>
			<address>
				<hi>2</hi>
				<mid>1</mid>
			</address>
			<size>33</size>
			<opcode ID = "variation_type">
				<address>
					<lo>64</lo>
				</address>
				<byteCount>2</byteCount>
				<byteType>MIDIBYTE</byteType>
				<valueClass>Integer</valueClass>
			</opcode>
			<opcode ID = "variation_1">
				<address>
					<lo>66</lo>
				</address>
				<byteCount>2</byteCount>
			</opcode>
			<opcode ID = "variation_2">
				<address>
					<lo>68</lo>
				</address>
				<byteCount>2</byteCount>
			</opcode>
			<opcode ID = "variation_3">
				<address>
					<lo>70</lo>
				</address>
				<byteCount>2</byteCount>
			</opcode>
			<opcode ID = "variation_4">
				<address>
					<lo>72</lo>
				</address>
				<byteCount>2</byteCount>
			</opcode>
			<opcode ID = "variation_5">
				<address>
					<lo>74</lo>
				</address>
				<byteCount>2</byteCount>
			</opcode>
			<opcode ID = "variation_6">
				<address>
					<lo>76</lo>
				</address>
				<byteCount>2</byteCount>
			</opcode>
			<opcode ID = "variation_7">
				<address>
					<lo>78</lo>
				</address>
				<byteCount>2</byteCount>
			</opcode>
			<opcode ID = "variation_8">
				<address>
					<lo>80</lo>
				</address>
				<byteCount>2</byteCount>
			</opcode>
			<opcode ID = "variation_9">
				<address>
					<lo>82</lo>
				</address>
				<byteCount>2</byteCount>
			</opcode>
			<opcode ID = "variation_10">
				<address>
					<lo>84</lo>
				</address>
				<byteCount>2</byteCount>
			</opcode>
			<opcode ID = "variation_return">
				<address>
					<lo>86</lo>
				</address>
			</opcode>
			<opcode ID = "variation_panorama">
				<address>
					<lo>87</lo>
				</address>
			</opcode>
			<opcode ID = "variation_to_reverb">
				<address>
					<lo>88</lo>
				</address>
			</opcode>
			<opcode ID = "variation_to_chorus">
				<address>
					<lo>89</lo>
				</address>
			</opcode>
			<opcode ID = "variation_connection">
				<address>
					<lo>90</lo>
				</address>
			</opcode>
			<opcode ID = "variation_part">
				<address>
					<lo>91</lo>
				</address>
			</opcode>
			<opcode ID = "variation_mw">
				<address>
					<lo>92</lo>
				</address>
			</opcode>
			<opcode ID = "variation_pb">
				<address>
					<lo>93</lo>
				</address>
			</opcode>
			<opcode ID = "variation_cat">
				<address>
					<lo>94</lo>
				</address>
			</opcode>
			<opcode ID = "variation_ac1">
				<address>
					<lo>95</lo>
				</address>
			</opcode>
			<opcode ID = "variation_ac2">
				<address>
					<lo>96</lo>
				</address>
			</opcode>
		</bulk>
		<bulk>
			<address>
				<hi>2</hi>
				<mid>1</mid>
			</address>
			<size>1</size>
			<opcode ID = "variation_cbc1">
				<address>
					<lo>97</lo>
				</address>
			</opcode>
		</bulk>
		<bulk>
			<address>
				<hi>2</hi>
				<mid>1</mid>
			</address>
			<size>1</size>
			<opcode ID = "variation_cbc2">
				<address>
					<lo>98</lo>
				</address>
			</opcode>
		</bulk>
		<bulk>
			<address>
				<hi>2</hi>
				<mid>1</mid>
			</address>
			<size>6</size>
			<opcode ID = "variation_11">
				<address>
					<lo>112</lo>
				</address>
			</opcode>
			<opcode ID = "variation_12">
				<address>
					<lo>113</lo>
				</address>
			</opcode>
			<opcode ID = "variation_13">
				<address>
					<lo>114</lo>
				</address>
			</opcode>
			<opcode ID = "variation_14">
				<address>
					<lo>115</lo>
				</address>
			</opcode>
			<opcode ID = "variation_15">
				<address>
					<lo>116</lo>
				</address>
			</opcode>
			<opcode ID = "variation_16">
				<address>
					<lo>117</lo>
				</address>
			</opcode>
		</bulk>
	</module>
	<module ID = "syseq">
		<name>System EQ</name>
		<address>
			<hi>2</hi>
			<mid>64</mid>
		</address>
		<bulk>
			<address>
				<hi>2</hi>
				<mid>64</mid>
			</address>
			<size>15</size>
			<opcode ID = "eq_type">
				<address>
					<lo>0</lo>
				</address>
			</opcode>
			<opcode ID = "eq_gain1">
				<address>
					<lo>1</lo>
				</address>
			</opcode>
			<opcode ID = "eq_frequency1">
				<address>
					<lo>2</lo>
