=== Fausti1971/JXG/rsc/xsd/fx-program.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="items">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="msb" use="required" type="xs:nonNegativeInteger"/>
						<xs:attribute name ="lsb" use="required" type="xs:nonNegativeInteger"/>
						<xs:attribute name="name" use="required"/>
						<xs:attribute name="table" use="required" type="xs:string"/>
						<xs:attribute name="reverb" type="option"/>
						<xs:attribute name="chorus" type="option"/>
						<xs:attribute name="variation" type="option"/>
						<xs:attribute name="insertion" type="option"/>
						<xs:attribute name="address" use="optional" type="addressType" default="byte"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="option">
		<xs:restriction base="xs:string">
			<xs:enumeration value=" "/>
			<xs:enumeration value="+"/>
			<xs:enumeration value="-"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="addressType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="byte"/>
			<xs:enumeration value="word"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Fausti1971/JXG/rsc/XG/fx-program.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	" "= XG Standard, XGLite Standard (Space)
	"+"= XG Option, XGLite Option
	"-"= XG Standard, XGLite Option
-->

<items xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../xsd/fx-program.xsd">
	<item msb="0" lsb="0" name="No Effect" table="NO_EFFECT" reverb=" " chorus=" " variation="-" insertion="-"/>
	<item msb="1" lsb="0" name="Hall 1" table="HALL_1" reverb=" " variation="-" insertion="-"/>
	<item msb="1" lsb="1" name="Hall 2" table="HALL_2" reverb="-" variation="-" insertion="-"/>
	<item msb="1" lsb="2" name="Large Hall" table="LARGE_HALL" reverb="+" variation="+" insertion="+"/>
	<item msb="1" lsb="3" name="Medium Hall" table="MEDIUM_HALL" reverb="+" variation="+" insertion="+"/>
	<item msb="1" lsb="6" name="Hall M" table="HALL_M" reverb="+" variation="+" insertion="+"/>
	<item msb="1" lsb="7" name="Hall L" table="HALL_L" reverb="+" variation="+" insertion="+"/>

	<item msb="2" lsb="0" name="Room 1" table="ROOM_1" reverb=" " variation="-" insertion="-"/>
	<item msb="2" lsb="1" name="Room 2" table="ROOM_2" reverb="-" variation="-" insertion="-"/>
	<item msb="2" lsb="2" name="Room 3" table="ROOM_3" reverb="-" variation="-" insertion="-"/>
	<item msb="2" lsb="3" name="Warm Room" table="WARM_ROOM" reverb="+" variation="+" insertion="+"/>
	<item msb="2" lsb="4" name="Woody Room" table="WOODY_ROOM" reverb="+" variation="+" insertion="+"/>
	<item msb="2" lsb="5" name="Room S" table="ROOM_S" reverb="+" variation="+" insertion="+"/>
	<item msb="2" lsb="6" name="Room M" table="ROOM_M" reverb="+" variation="+" insertion="+"/>
	<item msb="2" lsb="7" name="Room L" table="ROOM_L" reverb="+" variation="+" insertion="+"/>

	<item msb="3" lsb="0" name="Stage 1" table="STAGE_1" reverb=" " variation="-" insertion="-"/>
	<item msb="3" lsb="1" name="Stage 2" table="STAGE_2" reverb="-" variation="-" insertion="-"/>

	<item msb="4" lsb="0" name="Plate" table="PLATE" reverb=" " variation="-" insertion="-"/>
	<item msb="4" lsb="1" name="Rich Plate " table="RICH_PLATE" reverb="+" variation="+" insertion="+"/>
	<item msb="4" lsb="7" name="GM Plate" table="GM_PLATE" reverb="+" variation="+" insertion="+"/>

	<item msb="5" lsb="0" name="Delay LCR" table="DELAY_LCR" variation="-" insertion="-" address="word"/>

	<item msb="6" lsb="0" name="Delay LR" table="DELAY_LR" variation="-" insertion="-" address="word"/>

	<item msb="7" lsb="0" name="Echo" table="ECHO" variation="-" insertion="-" address="word"/>

	<item msb="8" lsb="0" name="Cross Delay" table="CROSS_DELAY" variation="-" insertion="-" address="word"/>

	<item msb="9" lsb="0" name="Early Reflection 1" table="ER_1" variation="-" insertion="-"/>
	<item msb="9" lsb="1" name="Early Reflection 2" table="ER_2" variation="-" insertion="-"/>

	<item msb="10" lsb="0" name="Gate Reverb" table="ER_1" variation="-" insertion="-"/>

	<item msb="11" lsb="0" name="Reverse Gate" table="REVERSE_GATE" variation="-" insertion="-"/>

	<item msb="16" lsb="0" name="White Room" table="WHITE_ROOM" reverb="+" variation="+" insertion="+"/>

	<item msb="17" lsb="0" name="Tunnel" table="TUNNEL" reverb="+" variation="+" insertion="+"/>

	<item msb="18" lsb="0" name="Canyon" table="CANYON" reverb="+" variation="+" insertion="+"/>

	<item msb="19" lsb="0" name="Basement" table="BASEMENT" reverb="+" variation="+" insertion="+"/>

	<item msb="20" lsb="0" name="Karaoke 1" table="KARAOKE_1" variation="+" insertion="+"/>
	<item msb="20" lsb="1" name="Karaoke 2" table="KARAOKE_2" variation="+" insertion="+"/>
	<item msb="20" lsb="2" name="Karaoke 3" table="KARAOKE_3" variation="+" insertion="+"/>

	<item msb="21" lsb="0" name="Tempo Delay" table="TEMPO_DELAY" variation="+" insertion="+"/>
	<item msb="21" lsb="8" name="Tempo Echo" table="TEMPO_ECHO" variation="+" insertion="+"/>

	<item msb="22" lsb="0" name="Tempo Cross" table="TEMPO_CROSS" variation="+" insertion="+"/>

	<item msb="64" lsb="0" name="Thru" table="NO_EFFECT" variation="-" insertion="-"/>

	<item msb="65" lsb="0" name="Chorus 1" table="CHORUS_1" chorus=" " variation="-" insertion="-"/>
	<item msb="65" lsb="1" name="Chorus 2" table="CHORUS_2" chorus="-" variation="-" insertion="-"/>
	<item msb="65" lsb="2" name="Chorus 3" table="CHORUS_3" chorus="-" variation="-" insertion="-"/>
	<item msb="65" lsb="3" name="GM Chorus 1" table="GM_CHORUS_1" chorus="+" variation="+" insertion="+"/>
	<item msb="65" lsb="4" name="GM Chorus 2" table="GM_CHORUS_2" chorus="+" variation="+" insertion="+"/>
	<item msb="65" lsb="5" name="GM Chorus 3" table="GM_CHORUS_3" chorus="+" variation="+" insertion="+"/>
	<item msb="65" lsb="6" name="GM Chorus 4" table="GM_CHORUS_4" chorus="+" variation="+" insertion="+"/>
	<item msb="65" lsb="7" name="FB Chorus" table="FB_CHORUS" chorus="+" variation="+" insertion="+"/>
	<item msb="65" lsb="8" name="Chorus 4" table="CHORUS_4" chorus="+" variation="+" insertion="+"/>

	<item msb="66" lsb="0" name="Celeste 1" table="CELESTE_1" chorus=" " variation="-" insertion="-"/>
	<item msb="66" lsb="1" name="Celeste 2" table="CELESTE_2" chorus="-" variation="-" insertion="-"/>
	<item msb="66" lsb="2" name="Celeste 3" table="CELESTE_3" chorus="-" variation="-" insertion="-"/>
	<item msb="66" lsb="8" name="Celeste 4" table="CELESTE_4" chorus="+" variation="+" insertion="+"/>

	<item msb="67" lsb="0" name="Flanger 1" table="FLANGER_1" chorus=" " variation="-" insertion="-"/>
	<item msb="67" lsb="1" name="Flanger 2" table="FLANGER_2" chorus="-" variation="-" insertion="-"/>
	<item msb="67" lsb="7" name="GM Flanger" table="GM_FLANGER" chorus="+" variation="+" insertion="+"/>
	<item msb="67" lsb="8" name="Flanger 3" table="FLANGER_3" chorus="+" variation="+" insertion="+"/>

	<item msb="68" lsb="0" name="Symphonic" table="SYMPHONIC" chorus="+" variation="-" insertion="-"/>

	<item msb="69" lsb="0" name="Rotary Speaker" table="ROTARY_SPEAKER" variation="-" insertion="-"/>
	<item msb="69" lsb="1" name="Distortion + Rotary Speaker" table="DIST_ROTARY_SPEAKER" variation="+" insertion="+"/>
	<item msb="69" lsb="2" name="Overdrive + Rotary Speaker" table="OVERDRIVE_ROTARY_SPEAKER" variation="+" insertion="+"/>
	<item msb="69" lsb="3" name="Amp + Rotary Speaker" table="AMP_ROTARY_SPEAKER" variation="+" insertion="+"/>

	<item msb="70" lsb="0" name="Tremolo" table="TREMOLO" variation="-" insertion="-"/>

	<item msb="71" lsb="0" name="Auto Pan" table="AUTO_PAN" variation="-" insertion="-"/>

	<item msb="72" lsb="0" name="Phaser 1" table="PHASER_1" chorus="+" variation="-" insertion="-"/>
	<item msb="72" lsb="8" name="Phaser 2" table="PHASER_2" variation="+" insertion="+"/>

	<item msb="73" lsb="0" name="Distortion" table="DISTORTION" variation="-" insertion="-"/>
	<item msb="73" lsb="1" name="Compressor + Distortion" table="COMPRESSOR_DISTORTION"  variation="+" insertion="+"/>
	<item msb="73" lsb="8" name="Stereo Distortion" table="STEREO_DISTORTION"  variation="+" insertion="+"/>

	<item msb="74" lsb="0" name="Overdrive" table="OVERDRIVE" variation="-" insertion="-"/>
	<item msb="74" lsb="8" name="Stereo Overdrive" table="STEREO_OVERDRIVE"  variation="+" insertion="+"/>

	<item msb="75" lsb="0" name="Amp Simulator" table="AMP_SIMULATOR" variation="-" insertion="-"/>
	<item msb="75" lsb="1" name="Amp Simulator 2" table="AMP_SIMULATOR_2" variation="+" insertion="+"/>
	<item msb="75" lsb="8" name="Stereo Amp Simulator" table="STEREO_AMP_SIMULATOR" variation="+" insertion="+"/>

	<item msb="76" lsb="0" name="3-Band EQ" table="3_BAND_EQ" variation="-" insertion="-"/>

	<item msb="77" lsb="0" name="2-Band EQ" table="2_BAND_EQ" variation="-" insertion="-"/>

	<item msb="78" lsb="0" name="Auto Wah" table="AUTO_WAH" variation="-" insertion="-"/>
	<item msb="78" lsb="1" name="Auto Wah + Distortion" table="AUTO_WAH_DIST" variation="+" insertion="+"/>
	<item msb="78" lsb="2" name="Auto Wah + Overdrive" table="AUTO_WAH_OVERDRIVE" variation="+" insertion="+"/>

	<item msb="80" lsb="0" name="Pitch Change" table="PITCH_CHANGE" variation="+" insertion="+"/>
	<item msb="80" lsb="1" name="Pitch Change 2" table="PITCH_CHANGE_2" variation="+" insertion="+"/>

	<item msb="81" lsb="0" name="Harmonic Enhancer" table="HARMONIC_ENHANCER" variation="+" insertion="+"/>

	<item msb="82" lsb="0" name="Touch Wah 1" table="TOUCH_WAH_1" variation="+" insertion="+"/>
	<item msb="82" lsb="1" name="Touch Wah + Distortion" table="TOUCH_WAH_DIST" variation="+" insertion="+"/>
	<item msb="82" lsb="2" name="Touch Wah + Overdrive" table="TOUCH_WAH_OVERDRIVE" variation="+" insertion="+"/>
	<item msb="82" lsb="8" name="Touch Wah 2" table="TOUCH_WAH_2" variation="+" insertion="+"/>

	<item msb="83" lsb="0" name="Compressor" table="COMPRESSOR" variation="+" insertion="+"/>

	<item msb="84" lsb="0" name="Noise Gate" table="NOISE_GATE" variation="+" insertion="+"/>

	<item msb="85" lsb="0" name="Voice Cancel" table="VOICE_CANCEL" variation="+" insertion="+"/>

	<item msb="86" lsb="0" name="2-Way Rotary Speaker" table="2_WAY_ROTARY_SPEAKER" variation="+" insertion="+"/>
	<item msb="86" lsb="1" name="Distortion + 2-Way Rotary Speaker" table="DIST_2_WAY_ROTARY_SPEAKER" variation="+" insertion="+"/>
	<item msb="86" lsb="2" name="Overdrive + 2-Way Rotary Speaker" table="OVERDRIVE_2_WAY_ROTARY_SPEAKER" variation="+" insertion="+"/>
	<item msb="86" lsb="3" name="Amp Simulator+ 2-Way Rotary Speaker" table="AMP_2_WAY_ROTARY_SPEAKER" variation="+" insertion="+"/>

	<item msb="87" lsb="0" name="Ensemble Detune" table="ENSEMBLE_DETUNE" chorus="+" variation="+" insertion="+"/>

	<item msb="88" lsb="0" name="Ambience" table="AMBIENCE" variation="+" insertion="+"/>

	<item msb="89" lsb="0" name="Vocoder Harmony" table="VOCODER_HARMONY" variation="+" insertion="+"/>

	<item msb="90" lsb="0" name="Chordal Harmony" table="CHORDAL_HARMONY" variation="+" insertion="+"/>

	<item msb="91" lsb="0" name="Detune Harmony" table="DETUNE_HARMONY" variation="+" insertion="+"/>
