=== Fausti1971/JXG/rsc/xsd/parameter.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- xs: erforderlich, da "byteType" bereits anderweitig belegt ist -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all>
							<xs:element name="description" type="xs:string" minOccurs="0"/>
							<xs:element name="longName" type="xs:string" minOccurs="0"/>
							<xs:element name="shortName" type="xs:string" minOccurs="0"/>
							<xs:element name="valueMin" type="xs:nonNegativeInteger" minOccurs="0"/>
							<xs:element name="valueMax" type="xs:nonNegativeInteger" minOccurs="0"/>
							<xs:element name="translator" type="translatorType" minOccurs="0"/>
							<xs:element name="translationMap" minOccurs="0"/>
							<xs:element name="dependsOf" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="REF" type="xs:IDREF" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="mutableMapKey" type="mapKey" minOccurs="0"/>
						</xs:all>
					<xs:attribute name="ID" use="required" type="xs:ID"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="translatorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="translateToText"/>
			<xs:enumeration value="translateNot"/>
			<xs:enumeration value="translateToTextPlus1"/>
			<xs:enumeration value="translateDiv10"/>
			<xs:enumeration value="translateSub128Div10"/>
			<xs:enumeration value="translateMap"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="mapKey">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="16"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Fausti1971/JXG/rsc/XG/old/parameters_old.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--bei fehlendem Inhalt (aber vorhandenem Tag) wird Defaultwert benutzt:
	translator = translateToText, translateNot, translateToTextPlus1, translateDiv10, translateSub128Div10, translateMap
	translationMap = ""
	translationMapFilter = ""
	descriptionMapIndex = 0... (der Index des Descriptions in der MutableParameterMap)
	descriptionDependsOf = 0 (dezimal, Offset des die Description definierenden Parameters bspw. ReverbType...)
-->
<parameters xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../xsd/parameter.xsd">

	<item ID = "info_name">
		<longName>Model Name</longName>
		<shortName>Model</shortName>
	</item>

	<item ID = "display_letter">
		<longName>DisplayText</longName>
		<shortName>Text</shortName>
	</item>

	<item ID = "reverb_type">
		<longName>Reverb Program</longName>
		<shortName>RevPrg</shortName>
		<valueMin>0</valueMin>
		<valueMax>69</valueMax>
		<translator>translateMap</translator>
		<translationMap>fx_programs</translationMap>
	</item>

	<item ID = "reverb_1">
		<dependsOf REF = "reverb_type"/>
		<mutableMapKey>1</mutableMapKey>
	</item>

	<item ID = "mp_elRes">
		<longName>Element Reserve</longName>
		<shortName>ElmRsv</shortName>
		<valueMin>0</valueMin>
		<valueMax>32</valueMax>
		<translator>translateToText</translator>
	</item>
	<item ID = "mp_bankMsb">
		<longName>Bank Select MSB</longName>
		<shortName>BnkMSB</shortName>
		<valueMin>0</valueMin>
		<valueMax>127</valueMax>
		<translator>translateToText</translator>
	</item>

	<item ID = "mp_ch">
		<longName>MIDI Channel</longName>
		<shortName>Ch</shortName>
		<valueMin>0</valueMin>
		<valueMax>127</valueMax>
		<translator>translateMap</translator>
		<translationMap>midi_channels</translationMap>
	</item>

	<item ID = "mp_detune">
		<longName>Detune</longName>
		<shortName>Tune</shortName>
		<valueMin>0</valueMin>
		<valueMax>255</valueMax>
		<translator>translateSub128Div10</translator>
	</item>

	<item ID = "mp_envAtk">
		<longName>Attack Time</longName>
		<shortName>Atck</shortName>
		<valueMin>0</valueMin>
		<valueMax>127</valueMax>
	</item>

	<item ID = "ds_sourcekit">
		<longName>SourceDrumkit</longName>
		<shortName>src-dk</shortName>
		<valueMin>264241152</valueMin>
		<valueMax>2147483647</valueMax>
	</item>

	<item ID = "reverb_time">
		<longName>Reverb Time</longName>
		<shortName>RevTime</shortName>
		<valueMin>0</valueMin>
		<valueMax>69</valueMax>
		<translator>translateMap</translator>
		<translationMap>reverb_time</translationMap>
	</item>

</parameters>

=== Fausti1971/JXG/rsc/JXG/parameter.xml
<?xml version="1.0" encoding="UTF-8"?>
<parameters xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../xsd/parameter.xsd">
	<item ID="window_x">
		<valueMin>0</valueMin>
		<valueMax>2147483648</valueMax>
	</item>
	<item ID="window_y">
		<valueMin>0</valueMin>
		<valueMax>2147483648</valueMax>
	</item>
	<item ID="window_w">
		<valueMin>0</valueMin>
		<valueMax>2147483648</valueMax>
	</item>
	<item ID="window_h">
		<valueMin>0</valueMin>
		<valueMax>2147483648</valueMax>
	</item>
	<item ID="device_sysexid">
		<valueMin>0</valueMin>
		<valueMax>15</valueMax>
		<translator>translateToTextPlus1</translator>
	</item>
	<item ID="device_color">
		<valueMin>0</valueMin>
		<valueMax>2147483648</valueMax>
	</item>
	<item ID="device_midi_timeout">
		<valueMin>15</valueMin>
		<valueMax>1000</valueMax>
	</item>
	<item ID="device_midi_input">
		<translator>translateMap</translator>
		<translationMap>midi_input_map</translationMap>
	</item>
	<item ID="device_midi_output">
		<translator>translateMap</translator>
		<translationMap>midi_output_map</translationMap>
	</item>
	<item ID="device_name">
		<translator>translateToText</translator>
	</item>
	<item ID="device_defaultDumpFolder">
		<translator>translateToText</translator>
	</item>
	<item ID="device_lastDumpFile">
		<translator>translateToText</translator>
	</item>
</parameters>
