=== Fausti1971/JXG/rsc/xsd/tables.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="tables">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="table" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="table">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="item" maxOccurs="unbounded"/>
			</xs:sequence>
		<xs:attribute name="name" use="required" type="xs:ID"/>
		<xs:attribute name="unit" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="item">
		<xs:complexType>
			<xs:attribute name="msb" type="xs:nonNegativeInteger" use="optional"/>
			<xs:attribute name="lsb" type="xs:nonNegativeInteger" use="optional"/>
			<xs:attribute name="value" type="xs:nonNegativeInteger" use="optional"/>
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="tableFilter" type="xs:string" use="optional"/>
			<xs:attribute name="categories" type="xs:string" use="optional"/>
			<xs:attribute name="address" type="addressType"/>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="addressType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="byte"/>
			<xs:enumeration value="word"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Fausti1971/JXG/rsc/MU80/tables.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- TODO: doppelte name-eintrÃ¤ge per xsd verhindern -->
<tables xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../xsd/tables.xsd">
	<table name="midi_channels">
		<item value="0" name="A-01"/>
		<item value="1" name="A-02"/>
		<item value="2" name="A-03"/>
		<item value="3" name="A-04"/>
		<item value="4" name="A-05"/>
		<item value="5" name="A-06"/>
		<item value="6" name="A-07"/>
		<item value="7" name="A-08"/>
		<item value="8" name="A-09"/>
		<item value="9" name="A-10"/>
		<item value="10" name="A-11"/>
		<item value="11" name="A-12"/>
		<item value="12" name="A-13"/>
		<item value="13" name="A-14"/>
		<item value="14" name="A-15"/>
		<item value="15" name="A-16"/>
		<item value="16" name="B-01"/>
		<item value="17" name="B-02"/>
		<item value="18" name="B-03"/>
		<item value="19" name="B-04"/>
		<item value="20" name="B-05"/>
		<item value="21" name="B-06"/>
		<item value="22" name="B-07"/>
		<item value="23" name="B-08"/>
		<item value="24" name="B-09"/>
		<item value="25" name="B-10"/>
		<item value="26" name="B-11"/>
		<item value="27" name="B-12"/>
		<item value="28" name="B-13"/>
		<item value="29" name="B-14"/>
		<item value="30" name="B-15"/>
		<item value="31" name="B-16"/>
		<item value="127" name="Off"/>
	</table>

	<table name="fx_programs">
		<item msb="0" lsb="0" name="No Effect" tableFilter="reverb,chorus,variation,insertion"/>
		<item msb="1" lsb="0" name="Hall 1" tableFilter="reverb,variation,insertion"/>
		<item msb="1" lsb="1" name="Hall 2" tableFilter="reverb,variation,insertion"/>
		<item msb="1" lsb="2" name="Large Hall" tableFilter="reverb,variation,insertion"/>
		<item msb="1" lsb="3" name="Medium Hall" tableFilter="reverb,variation,insertion"/>
		<item msb="1" lsb="6" name="Hall M" tableFilter="reverb,variation,insertion"/>
		<item msb="1" lsb="7" name="Hall L" tableFilter="reverb,variation,insertion"/>
		<item msb="2" lsb="0" name="Room 1" tableFilter="reverb,variation,insertion"/>
		<item msb="2" lsb="1" name="Room 2" tableFilter="reverb,variation,insertion"/>
		<item msb="2" lsb="2" name="Room 3" tableFilter="reverb,variation,insertion"/>
		<item msb="2" lsb="3" name="Warm Room" tableFilter="reverb,variation,insertion"/>
		<item msb="2" lsb="4" name="Woody Room" tableFilter="reverb,variation,insertion"/>
		<item msb="2" lsb="5" name="Room S" tableFilter="reverb,variation,insertion"/>
		<item msb="2" lsb="6" name="Room M" tableFilter="reverb,variation,insertion"/>
		<item msb="2" lsb="7" name="Room L" tableFilter="reverb,variation,insertion"/>
		<item msb="3" lsb="0" name="Stage 1" tableFilter="reverb,variation,insertion"/>
		<item msb="3" lsb="1" name="Stage 2" tableFilter="reverb,variation,insertion"/>
		<item msb="4" lsb="0" name="Plate" tableFilter="reverb,variation,insertion"/>
		<item msb="4" lsb="1" name="Rich Plate" tableFilter="reverb,variation,insertion"/>
		<item msb="4" lsb="7" name="GM Plate" tableFilter="reverb,variation,insertion"/>
		<item msb="5" lsb="0" name="Delay LCR" tableFilter="variation,insertion" address="word"/>
		<item msb="6" lsb="0" name="Delay LR" tableFilter="variation,insertion" address="word"/>
		<item msb="7" lsb="0" name="Echo" tableFilter="variation,insertion" address="word"/>
		<item msb="8" lsb="0" name="Cross Delay" tableFilter="variation,insertion" address="word"/>
		<item msb="9" lsb="0" name="Early Reflection 1" tableFilter="variation,insertion"/>
		<item msb="9" lsb="1" name="Early Reflection 2" tableFilter="variation,insertion"/>
		<item msb="10" lsb="0" name="Gate Reverb" tableFilter="variation,insertion"/>
		<item msb="11" lsb="0" name="Reverse Gate" tableFilter="variation,insertion"/>
		<item msb="16" lsb="0" name="White Room" tableFilter="reverb,variation,insertion"/>
		<item msb="17" lsb="0" name="Tunnel" tableFilter="reverb,variation,insertion"/>
		<item msb="18" lsb="0" name="Canyon" tableFilter="reverb,variation,insertion"/>
		<item msb="19" lsb="0" name="Basement" tableFilter="reverb,variation,insertion"/>
		<item msb="20" lsb="0" name="Karaoke 1" tableFilter="variation,insertion"/>
		<item msb="20" lsb="1" name="Karaoke 2" tableFilter="variation,insertion"/>
		<item msb="20" lsb="2" name="Karaoke 3" tableFilter="variation,insertion"/>
		<item msb="21" lsb="0" name="Tempo Delay" tableFilter="variation,insertion"/>
		<item msb="21" lsb="8" name="Tempo Echo" tableFilter="variation,insertion"/>
		<item msb="22" lsb="0" name="Tempo Cross" tableFilter="variation,insertion"/>
		<item msb="64" lsb="0" name="Thru" tableFilter="variation,insertion"/>
		<item msb="65" lsb="0" name="Chorus 1" tableFilter="chorus,variation,insertion"/>
		<item msb="65" lsb="1" name="Chorus 2" tableFilter="chorus,variation,insertion"/>
		<item msb="65" lsb="2" name="Chorus 3" tableFilter="chorus,variation,insertion"/>
		<item msb="65" lsb="3" name="GM Chorus 1" tableFilter="chorus,variation,insertion"/>
		<item msb="65" lsb="4" name="GM Chorus 2" tableFilter="chorus,variation,insertion"/>
		<item msb="65" lsb="5" name="GM Chorus 3" tableFilter="chorus,variation,insertion"/>
		<item msb="65" lsb="6" name="GM Chorus 4" tableFilter="chorus,variation,insertion"/>
		<item msb="65" lsb="7" name="FB Chorus" tableFilter="chorus,variation,insertion"/>
		<item msb="65" lsb="8" name="Chorus 4" tableFilter="chorus,variation,insertion"/>
		<item msb="66" lsb="0" name="Celeste 1" tableFilter="chorus,variation,insertion"/>
		<item msb="66" lsb="1" name="Celeste 2" tableFilter="chorus,variation,insertion"/>
		<item msb="66" lsb="2" name="Celeste 3" tableFilter="chorus,variation,insertion"/>
		<item msb="66" lsb="8" name="Celeste 4" tableFilter="chorus,variation,insertion"/>
		<item msb="67" lsb="0" name="Flanger 1" tableFilter="chorus,variation,insertion"/>
		<item msb="67" lsb="1" name="Flanger 2" tableFilter="chorus,variation,insertion"/>
		<item msb="67" lsb="7" name="GM Flanger" tableFilter="chorus,variation,insertion"/>
		<item msb="67" lsb="8" name="Flanger 3" tableFilter="chorus,variation,insertion"/>
		<item msb="68" lsb="0" name="Symphonic" tableFilter="chorus,variation,insertion"/>
		<item msb="69" lsb="0" name="Rotary Speaker" tableFilter="variation,insertion"/>
		<item msb="69" lsb="1" name="Distortion + Rotary Speaker" tableFilter="variation,insertion"/>
		<item msb="69" lsb="2" name="Overdrive + Rotary Speaker" tableFilter="variation,insertion"/>
		<item msb="69" lsb="3" name="Amp + Rotary Speaker" tableFilter="variation,insertion"/>
		<item msb="70" lsb="0" name="Tremolo" tableFilter="variation,insertion"/>
		<item msb="71" lsb="0" name="Auto Pan" tableFilter="variation,insertion"/>
		<item msb="72" lsb="0" name="Phaser 1" tableFilter="chorus,variation,insertion"/>
		<item msb="72" lsb="8" name="Phaser 2" tableFilter="variation,insertion"/>
		<item msb="73" lsb="0" name="Distortion" tableFilter="variation,insertion"/>
		<item msb="73" lsb="1" name="Compressor + Distortion" tableFilter="variation,insertion"/>
		<item msb="73" lsb="8" name="Stereo Distortion" tableFilter="variation,insertion"/>
		<item msb="74" lsb="0" name="Overdrive" tableFilter="variation,insertion"/>
		<item msb="74" lsb="8" name="Stereo Overdrive"  tableFilter="variation,insertion"/>
		<item msb="75" lsb="0" name="Amp Simulator" tableFilter="variation,insertion"/>
		<item msb="75" lsb="1" name="Amp Simulator 2" tableFilter="variation,insertion"/>
		<item msb="75" lsb="8" name="Stereo Amp Simulator" tableFilter="variation,insertion"/>
		<item msb="76" lsb="0" name="3-Band EQ" tableFilter="variation,insertion"/>
		<item msb="77" lsb="0" name="2-Band EQ" tableFilter="variation,insertion"/>
		<item msb="78" lsb="0" name="Auto Wah" tableFilter="variation,insertion"/>
		<item msb="78" lsb="1" name="Auto Wah + Distortion" tableFilter="variation,insertion"/>
		<item msb="78" lsb="2" name="Auto Wah + Overdrive" tableFilter="variation,insertion"/>
		<item msb="80" lsb="0" name="Pitch Change" tableFilter="variation,insertion"/>
		<item msb="80" lsb="1" name="Pitch Change 2" tableFilter="variation,insertion"/>
		<item msb="81" lsb="0" name="Harmonic Enhancer" tableFilter="variation,insertion"/>
		<item msb="82" lsb="0" name="Touch Wah 1" tableFilter="variation,insertion"/>
		<item msb="82" lsb="1" name="Touch Wah + Distortion" tableFilter="variation,insertion"/>
		<item msb="82" lsb="2" name="Touch Wah + Overdrive" tableFilter="variation,insertion"/>
		<item msb="82" lsb="8" name="Touch Wah 2" tableFilter="variation,insertion"/>
		<item msb="83" lsb="0" name="Compressor" tableFilter="variation,insertion"/>
		<item msb="84" lsb="0" name="Noise Gate" tableFilter="variation,insertion"/>
		<item msb="85" lsb="0" name="Voice Cancel" tableFilter="variation,insertion"/>
		<item msb="86" lsb="0" name="2-Way Rotary Speaker" tableFilter="variation,insertion"/>
		<item msb="86" lsb="1" name="Distortion + 2-Way Rotary Speaker" tableFilter="variation,insertion"/>
		<item msb="86" lsb="2" name="Overdrive + 2-Way Rotary Speaker" tableFilter="variation,insertion"/>
		<item msb="86" lsb="3" name="Amp Simulator+ 2-Way Rotary Speaker" tableFilter="variation,insertion"/>
		<item msb="87" lsb="0" name="Ensemble Detune" tableFilter="chorus,variation,insertion"/>
		<item msb="88" lsb="0" name="Ambience" tableFilter="variation,insertion"/>
		<item msb="89" lsb="0" name="Vocoder Harmony" tableFilter="variation,insertion"/>
		<item msb="90" lsb="0" name="Chordal Harmony" tableFilter="variation,insertion"/>
		<item msb="91" lsb="0" name="Detune Harmony" tableFilter="variation,insertion"/>
		<item msb="92" lsb="0" name="Chromatic Harmony" tableFilter="variation,insertion"/>
		<item msb="93" lsb="0" name="Talking Modulator" tableFilter="variation,insertion"/>
		<item msb="94" lsb="0" name="LoFi" tableFilter="variation,insertion"/>
		<item msb="95" lsb="0" name="Distortion + Delay" tableFilter="variation,insertion" address="word"/>
		<item msb="95" lsb="1" name="Overdrive + Delay" tableFilter="variation,insertion" address="word"/>
