=== Fausti1971/JXG/rsc/xsd/template.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="frame" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="frame">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="frame" maxOccurs="unbounded"/>
				<xs:element ref="knob" maxOccurs="unbounded"/>
				<xs:element ref="slider" maxOccurs="unbounded"/>
				<xs:element ref="combo" maxOccurs="unbounded"/>
				<xs:element ref="radio" maxOccurs="unbounded"/>
				<xs:element ref="envelope" maxOccurs="unbounded"/>
				<xs:element ref="auto" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attribute name="id" use="required" type="xs:NCName"/>
			<xs:attribute name="name" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="knob">
		<xs:complexType>
			<xs:attribute name="value" use="required" type="address"/>
			<xs:attribute name="axis" use="optional" type="axis" default="x"/>
			<xs:attribute name="origin" use="optional" type="origin" default="left"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="slider">
	</xs:element>

	<xs:element name="combo">
	</xs:element>

	<xs:element name="radio">
	</xs:element>

	<xs:element name="envelope">
	</xs:element>

	<xs:element name="auto">
	</xs:element>

	<xs:simpleType name="origin">
		<xs:restriction base="xs:string">
			<xs:enumeration value="left"/>
			<xs:enumeration value="center"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="axis">
		<xs:restriction base="xs:string">
			<xs:enumeration value="x"/>
			<xs:enumeration value="y"/>
			<xs:enumeration value="xy"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="address">
		<xs:restriction base="xs:string">
			<xs:pattern value="([\d]+|[\d]+-[\d]+)?\/([\d]+|[\d]+-[\d]+)?\/([\d]+|[\d]+-[\d]+)?"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== Fausti1971/JXG/rsc/MU80/templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../xsd/template.xsd">
	<frame address="0/0/" grid="0,0,0,0">
		<knob value="0/0/0" grid="0,0,1,1"/>
		<knob value="0/0/4" grid="1,0,1,1"/>
		<knob value="0/0/5" grid="2,0,1,1"/>
		<knob value="0/0/6" grid="3,0,1,1"/>
	</frame>
	<frame address="2/1/0-21" grid="0,0,0,0">
		<combo value="2/1/0" grid="0,0,5,1" grid_fill="1"/>
		<knob value="2/1/12" grid="5,0,1,1"/>
		<knob value="2/1/13" grid="6,0,1,1"/>

		<knob value="2/1/2" grid="0,1,1,1"/>
		<knob value="2/1/3" grid="1,1,1,1"/>
		<knob value="2/1/4" grid="2,1,1,1"/>
		<knob value="2/1/5" grid="3,1,1,1"/>
		<knob value="2/1/6" grid="4,1,1,1"/>
		<knob value="2/1/7" grid="5,1,1,1"/>
		<knob value="2/1/8" grid="6,1,1,1"/>
		<knob value="2/1/9" grid="7,1,1,1"/>
		<knob value="2/1/10" grid="8,1,1,1"/>
		<knob value="2/1/11" grid="9,1,1,1"/>
		<knob value="2/1/16" grid="10,1,1,1"/>
		<knob value="2/1/17" grid="11,1,1,1"/>
		<knob value="2/1/18" grid="12,1,1,1"/>
		<knob value="2/1/19" grid="13,1,1,1"/>
		<knob value="2/1/20" grid="14,1,1,1"/>
		<knob value="2/1/21" grid="15,1,1,1"/>
	</frame>

	<frame address="2/1/32-53"  grid="0,0,0,0">
		<combo value="2/1/32" grid="0,0,5,1" grid_fill="1"/>
		<knob value="2/1/44" grid="5,0,1,1"/>
		<knob value="2/1/45" grid="6,0,1,1"/>
		<knob value="2/1/46" grid="7,0,1,1"/>

		<knob value="2/1/34" grid="0,1,1,1"/>
		<knob value="2/1/35" grid="1,1,1,1"/>
		<knob value="2/1/36" grid="2,1,1,1"/>
		<knob value="2/1/37" grid="3,1,1,1"/>
		<knob value="2/1/38" grid="4,1,1,1"/>
		<knob value="2/1/39" grid="5,1,1,1"/>
		<knob value="2/1/40" grid="6,1,1,1"/>
		<knob value="2/1/41" grid="7,1,1,1"/>
		<knob value="2/1/42" grid="8,1,1,1"/>
		<knob value="2/1/43" grid="9,1,1,1"/>
		<knob value="2/1/48" grid="10,1,1,1"/>
		<knob value="2/1/49" grid="11,1,1,1"/>
		<knob value="2/1/50" grid="12,1,1,1"/>
		<knob value="2/1/51" grid="13,1,1,1"/>
		<knob value="2/1/52" grid="14,1,1,1"/>
		<knob value="2/1/53" grid="15,1,1,1"/>
	</frame>

	<frame address="2/1/64-117"  grid="0,0,0,0">
		<combo value="2/1/64" grid="0,0,5,1" grid_fill="1"/>
		<knob value="2/1/86" grid="5,0,1,1"/>
		<knob value="2/1/87" grid="6,0,1,1"/>
		<knob value="2/1/88" grid="7,0,1,1"/>
		<knob value="2/1/89" grid="8,0,1,1"/>
		<radio value="2/1/90" grid="9,0,2,1" grid_fill="3"/>
		<knob value="2/1/91" grid="11,0,1,1"/>

		<knob value="2/1/92" grid="0,1,1,1"/>
		<knob value="2/1/93" grid="1,1,1,1"/>
		<knob value="2/1/94" grid="2,1,1,1"/>
		<knob value="2/1/95" grid="3,1,1,1"/>
		<knob value="2/1/96" grid="4,1,1,1"/>
		<knob value="2/1/97" grid="5,1,1,1"/>
		<knob value="2/1/98" grid="6,1,1,1"/>

		<knob value="2/1/66" grid="0,2,1,1"/>
		<knob value="2/1/68" grid="1,2,1,1"/>
		<knob value="2/1/70" grid="2,2,1,1"/>
		<knob value="2/1/72" grid="3,2,1,1"/>
		<knob value="2/1/74" grid="4,2,1,1"/>
		<knob value="2/1/76" grid="5,2,1,1"/>
		<knob value="2/1/78" grid="6,2,1,1"/>
		<knob value="2/1/80" grid="7,2,1,1"/>
		<knob value="2/1/82" grid="8,2,1,1"/>
		<knob value="2/1/84" grid="9,2,1,1"/>

		<knob value="2/1/112" grid="10,2,1,1"/>
		<knob value="2/1/113" grid="11,2,1,1"/>
		<knob value="2/1/114" grid="12,2,1,1"/>
		<knob value="2/1/115" grid="13,2,1,1"/>
		<knob value="2/1/116" grid="14,2,1,1"/>
		<knob value="2/1/117" grid="15,2,1,1"/>
	</frame>
	<frame address="3//" grid="0,0,0,0">
		<combo value="3//0" grid="0,0,5,1" grid_fill="1"/>
		<knob value="3//12" grid="5,0,1,1"/>

		<knob value="3//13" grid="0,1,1,1"/>
		<knob value="3//14" grid="1,1,1,1"/>
		<knob value="3//15" grid="2,1,1,1"/>
		<knob value="3//16" grid="3,1,1,1"/>
		<knob value="3//17" grid="4,1,1,1"/>
		<knob value="3//18" grid="5,1,1,1"/>
		<knob value="3//19" grid="6,1,1,1"/>

		<knob value="3//2" grid="0,2,1,1"/>
		<knob value="3//3" grid="1,2,1,1"/>
		<knob value="3//4" grid="2,2,1,1"/>
		<knob value="3//5" grid="3,2,1,1"/>
		<knob value="3//6" grid="4,2,1,1"/>
		<knob value="3//7" grid="5,2,1,1"/>
		<knob value="3//8" grid="6,2,1,1"/>
		<knob value="3//9" grid="7,2,1,1"/>
		<knob value="3//10" grid="8,2,1,1"/>
		<knob value="3//11" grid="9,2,1,1"/>
		<knob value="3//32" grid="10,2,1,1"/>
		<knob value="3//33" grid="11,2,1,1"/>
		<knob value="3//34" grid="12,2,1,1"/>
		<knob value="3//35" grid="13,2,1,1"/>
		<knob value="3//36" grid="14,2,1,1"/>
		<knob value="3//37" grid="15,2,1,1"/>
	</frame>

	<frame address="8-10//" grid="0,0,0,0">
		<frame address="8-10//" name="Midi" grid="0,0,0,0">
			<combo value="8//4" grid="0,0,2,1" grid_fill="3"/>
			<knob value="8//12" grid="2,0,1,1"/>
		</frame>
		<frame address="8-10//" name="Voice" grid="0,1,0,0" grid_fill="1">
			<radio value="8//5" grid="0,0,2,1" grid_fill="3"/>
			<radio value="8//6" grid="0,1,2,2" grid_fill="3"/>
			<radio value="8//7" grid="0,3,2,3" grid-fill="3"/>
			<knob value="8//0" grid="2,0,1,1"/>
			<knob value="8//8" grid="3,0,1,1"/>
			<knob value="8//9-10" grid="4,0,1,1"/>
			<knob value="8//11" grid="5,0,1,1"/>
			<envelope name="Amp Envelope Generator"  grid="4,0,8,4">
				<point value_x="0/0/0" value_y="0/0/0"/>
				<point value_x="8//26" value_y="8//11"/>
				<point value_x="8//27" value_y="8//11"/>
				<point value_x="8//28" value_y="0/0/0"/>
			</envelope>
		</frame>
	</frame>
</templates>
