=== Fausti1971/JXG/rsc/xsd/translation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="maps">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="map">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="entry" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="value" type="xs:nonNegativeInteger"/>
										<xs:element name="text" type="xs:string"/>
									</xs:sequence>
								<xs:attribute name="filter" type="xs:string" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					<xs:attribute name="name" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Fausti1971/JXG/rsc/MU80/translation.xml
<?xml version="1.0" encoding="UTF-8"?>
<maps xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../xsd/translation.xsd">
	<map name="midi_channels">
		<entry>
			<value>0</value>
			<text>A-01</text>
		</entry>
		<entry>
			<value>1</value>
			<text>A-02</text>
		</entry>
		<entry>
			<value>2</value>
			<text>A-03</text>
		</entry>
		<entry>
			<value>3</value>
			<text>A-04</text>
		</entry>
		<entry>
			<value>4</value>
			<text>A-05</text>
		</entry>
		<entry>
			<value>5</value>
			<text>A-06</text>
		</entry>
		<entry>
			<value>6</value>
			<text>A-07</text>
		</entry>
		<entry>
			<value>7</value>
			<text>A-08</text>
		</entry>
		<entry>
			<value>8</value>
			<text>A-09</text>
		</entry>
		<entry>
			<value>9</value>
			<text>A-10</text>
		</entry>
		<entry>
			<value>10</value>
			<text>A-11</text>
		</entry>
		<entry>
			<value>11</value>
			<text>A-12</text>
		</entry>
		<entry>
			<value>12</value>
			<text>A-13</text>
		</entry>
		<entry>
			<value>13</value>
			<text>A-14</text>
		</entry>
		<entry>
			<value>14</value>
			<text>A-15</text>
		</entry>
		<entry>
			<value>15</value>
			<text>A-16</text>
		</entry>
		<entry>
			<value>16</value>
			<text>B-01</text>
		</entry>
		<entry>
			<value>17</value>
			<text>B-02</text>
		</entry>
		<entry>
			<value>18</value>
			<text>B-03</text>
		</entry>
		<entry>
			<value>19</value>
			<text>B-04</text>
		</entry>
		<entry>
			<value>20</value>
			<text>B-05</text>
		</entry>
		<entry>
			<value>21</value>
			<text>B-06</text>
		</entry>
		<entry>
			<value>22</value>
			<text>B-07</text>
		</entry>
		<entry>
			<value>23</value>
			<text>B-08</text>
		</entry>
		<entry>
			<value>24</value>
			<text>B-09</text>
		</entry>
		<entry>
			<value>25</value>
			<text>B-10</text>
		</entry>
		<entry>
			<value>26</value>
			<text>B-11</text>
		</entry>
		<entry>
			<value>27</value>
			<text>B-12</text>
		</entry>
		<entry>
			<value>28</value>
			<text>B-13</text>
		</entry>
		<entry>
			<value>29</value>
			<text>B-14</text>
		</entry>
		<entry>
			<value>30</value>
			<text>B-15</text>
		</entry>
		<entry>
			<value>31</value>
			<text>B-16</text>
		</entry>
		<entry>
			<value>127</value>
			<text>Off</text>
		</entry>
	</map>
</maps>
