=== Fausti1971/JXG/rsc/default.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="defaultTables">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="defaultTable" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="defaultTable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="default" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		<xs:attribute name="name" use="required" type="xs:NCName"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="default">
		<xs:complexType>
			<xs:attribute name="selectorValue" type="valueType" use="required"/>
			<xs:attribute name="default" type="valueType" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="valueType">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d+((\.\d+)+)?"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Fausti1971/JXG/xml/XG/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<defaultTables xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../xsd/default.xsd">
	<defaultTable name="fx_parameter_1">
		<default selectorValue="118.0" default="80"/>
		<default selectorValue="7.0" default="1700"/>
		<default selectorValue="102.0" default="11"/>
		<default selectorValue="88.0" default="114"/>
		<default selectorValue="127.2" default="64"/>
		<default selectorValue="2.0" default="5"/>
		<default selectorValue="92.0" default="0"/>
		<default selectorValue="73.8" default="18"/>
		<default selectorValue="20.0" default="63"/>
		<default selectorValue="2.6" default="13"/>
		<default selectorValue="1.2" default="18"/>
		<default selectorValue="66.1" default="28"/>
		<default selectorValue="2.7" default="15"/>
		<default selectorValue="67.7" default="3"/>
		<default selectorValue="95.0" default="2500"/>
		<default selectorValue="21.8" default="11"/>
		<default selectorValue="114.0" default="5"/>
		<default selectorValue="67.8" default="4"/>
		<default selectorValue="80.1" default="65"/>
		<default selectorValue="4.7" default="13"/>
		<default selectorValue="82.0" default="36"/>
		<default selectorValue="65.3" default="9"/>
		<default selectorValue="5.0" default="3333"/>
		<default selectorValue="86.2" default="5"/>
		<default selectorValue="9.0" default="0"/>
		<default selectorValue="105.0" default="9"/>
		<default selectorValue="67.1" default="32"/>
		<default selectorValue="81.0" default="44"/>
		<default selectorValue="98.2" default="13"/>
		<default selectorValue="91.0" default="0"/>
		<default selectorValue="127.3" default="89"/>
		<default selectorValue="73.1" default="40"/>
		<default selectorValue="93.0" default="0"/>
		<default selectorValue="107.0" default="17"/>
		<default selectorValue="101.0" default="11"/>
		<default selectorValue="69.2" default="7"/>
		<default selectorValue="20.2" default="43"/>
		<default selectorValue="72.0" default="8"/>
		<default selectorValue="100.1" default="11"/>
		<default selectorValue="75.8" default="16"/>
		<default selectorValue="101.1" default="11"/>
		<default selectorValue="68.0" default="12"/>
		<default selectorValue="71.1" default="67"/>
		<default selectorValue="108.0" default="17"/>
		<default selectorValue="116.0" default="3"/>
		<default selectorValue="78.2" default="48"/>
		<default selectorValue="4.1" default="23"/>
		<default selectorValue="2.4" default="5"/>
		<default selectorValue="96.1" default="3000"/>
		<default selectorValue="65.2" default="4"/>
		<default selectorValue="2.5" default="11"/>
		<default selectorValue="69.3" default="5"/>
		<default selectorValue="2.3" default="3"/>
		<default selectorValue="65.1" default="8"/>
		<default selectorValue="1.1" default="25"/>
		<default selectorValue="80.0" default="64"/>
		<default selectorValue="9.1" default="2"/>
		<default selectorValue="127.1" default="64"/>
		<default selectorValue="97.0" default="1600"/>
		<default selectorValue="82.1" default="36"/>
		<default selectorValue="109.0" default="1"/>
		<default selectorValue="84.0" default="0"/>
		<default selectorValue="6.0" default="2500"/>
		<default selectorValue="69.0" default="81"/>
		<default selectorValue="77.0" default="28"/>
		<default selectorValue="82.2" default="45"/>
		<default selectorValue="103.1" default="14"/>
		<default selectorValue="86.3" default="8"/>
		<default selectorValue="119.0" default="69"/>
		<default selectorValue="65.4" default="26"/>
		<default selectorValue="104.0" default="5"/>
		<default selectorValue="66.8" default="8"/>
		<default selectorValue="75.0" default="39"/>
		<default selectorValue="2.2" default="9"/>
		<default selectorValue="115.0" default="1"/>
		<default selectorValue="21.0" default="10"/>
		<default selectorValue="66.2" default="4"/>
		<default selectorValue="3.1" default="11"/>
		<default selectorValue="111.0" default="98"/>
		<default selectorValue="1.7" default="18"/>
		<default selectorValue="22.0" default="8"/>
		<default selectorValue="102.1" default="11"/>
		<default selectorValue="66.0" default="12"/>
		<default selectorValue="103.0" default="22"/>
		<default selectorValue="86.0" default="16"/>
		<default selectorValue="69.1" default="6"/>
		<default selectorValue="1.6" default="18"/>
		<default selectorValue="3.0" default="19"/>
		<default selectorValue="65.8" default="9"/>
		<default selectorValue="4.0" default="25"/>
		<default selectorValue="78.0" default="70"/>
		<default selectorValue="99.0" default="15"/>
		<default selectorValue="95.1" default="1900"/>
		<default selectorValue="96.0" default="3000"/>
		<default selectorValue="82.8" default="68"/>
		<default selectorValue="65.0" default="6"/>
		<default selectorValue="65.7" default="6"/>
		<default selectorValue="76.0" default="70"/>
		<default selectorValue="94.0" default="2"/>
		<default selectorValue="10.0" default="0"/>
		<default selectorValue="90.0" default="0"/>
		<default selectorValue="70.0" default="83"/>
		<default selectorValue="17.0" default="48"/>
		<default selectorValue="100.0" default="11"/>
		<default selectorValue="97.1" default="1600"/>
		<default selectorValue="71.0" default="76"/>
		<default selectorValue="11.0" default="1"/>
		<default selectorValue="78.1" default="40"/>
		<default selectorValue="20.1" default="55"/>
		<default selectorValue="83.0" default="6"/>
		<default selectorValue="110.0" default="122"/>
		<default selectorValue="98.0" default="22"/>
		<default selectorValue="112.0" default="70"/>
		<default selectorValue="74.8" default="10"/>
		<default selectorValue="72.8" default="8"/>
		<default selectorValue="86.1" default="6"/>
		<default selectorValue="2.1" default="12"/>
		<default selectorValue="65.5" default="9"/>
		<default selectorValue="1.0" default="18"/>
		<default selectorValue="19.0" default="3"/>
		<default selectorValue="117.0" default="1"/>
		<default selectorValue="18.0" default="59"/>
		<default selectorValue="67.0" default="14"/>
		<default selectorValue="1.3" default="15"/>
		<default selectorValue="16.0" default="9"/>
		<default selectorValue="98.3" default="14"/>
		<default selectorValue="75.1" default="50"/>
		<default selectorValue="87.0" default="54"/>
		<default selectorValue="74.0" default="29"/>
		<default selectorValue="65.6" default="26"/>
		<default selectorValue="113.0" default="98"/>
		<default selectorValue="73.0" default="40"/>
		<default selectorValue="99.1" default="14"/>
		<default selectorValue="89.0" default="0"/>
		<default selectorValue="8.0" default="1700"/>
		<default selectorValue="98.1" default="22"/>
	</defaultTable>
	<defaultTable name="fx_parameter_2">
		<default selectorValue="65.0" default="54"/>
		<default selectorValue="20.2" default="110"/>
		<default selectorValue="69.3" default="90"/>
		<default selectorValue="78.2" default="64"/>
		<default selectorValue="69.1" default="92"/>
		<default selectorValue="93.0" default="15"/>
		<default selectorValue="65.5" default="34"/>
		<default selectorValue="103.0" default="3"/>
		<default selectorValue="8.0" default="1750"/>
		<default selectorValue="6.0" default="3750"/>
		<default selectorValue="9.1" default="7"/>
		<default selectorValue="74.0" default="24"/>
		<default selectorValue="71.1" default="127"/>
		<default selectorValue="67.0" default="14"/>
		<default selectorValue="112.0" default="0"/>
		<default selectorValue="19.0" default="6"/>
		<default selectorValue="94.0" default="60"/>
		<default selectorValue="86.0" default="26"/>
		<default selectorValue="115.0" default="64"/>
		<default selectorValue="86.1" default="28"/>
		<default selectorValue="88.0" default="0"/>
		<default selectorValue="72.0" default="111"/>
		<default selectorValue="80.0" default="0"/>
		<default selectorValue="20.1" default="105"/>
		<default selectorValue="20.0" default="97"/>
		<default selectorValue="70.0" default="56"/>
		<default selectorValue="108.0" default="48"/>
		<default selectorValue="98.0" default="3"/>
		<default selectorValue="16.0" default="5"/>
		<default selectorValue="78.0" default="56"/>
		<default selectorValue="65.6" default="29"/>
		<default selectorValue="73.1" default="20"/>
		<default selectorValue="82.1" default="0"/>
		<default selectorValue="98.2" default="3"/>
		<default selectorValue="82.8" default="18"/>
		<default selectorValue="113.0" default="0"/>
		<default selectorValue="102.1" default="84"/>
		<default selectorValue="1.2" default="10"/>
		<default selectorValue="22.0" default="8"/>
		<default selectorValue="73.0" default="20"/>
		<default selectorValue="75.1" default="3"/>
		<default selectorValue="107.0" default="10"/>
		<default selectorValue="96.1" default="72"/>
		<default selectorValue="71.0" default="80"/>
		<default selectorValue="110.0" default="1"/>
		<default selectorValue="1.7" default="10"/>
		<default selectorValue="86.2" default="28"/>
		<default selectorValue="80.1" default="50"/>
		<default selectorValue="99.1" default="18"/>
		<default selectorValue="66.0" default="32"/>
		<default selectorValue="10.0" default="15"/>
		<default selectorValue="65.8" default="32"/>
		<default selectorValue="103.1" default="3"/>
		<default selectorValue="75.0" default="1"/>
		<default selectorValue="95.0" default="3000"/>
		<default selectorValue="118.0" default="1800"/>
		<default selectorValue="99.0" default="18"/>
		<default selectorValue="1.6" default="10"/>
		<default selectorValue="68.0" default="25"/>
		<default selectorValue="76.0" default="34"/>
		<default selectorValue="1.0" default="10"/>
		<default selectorValue="2.6" default="10"/>
		<default selectorValue="3.0" default="10"/>
		<default selectorValue="65.3" default="10"/>
		<default selectorValue="2.3" default="10"/>
		<default selectorValue="102.0" default="86"/>
		<default selectorValue="73.8" default="27"/>
		<default selectorValue="21.8" default="92"/>
		<default selectorValue="72.8" default="111"/>
		<default selectorValue="74.8" default="24"/>
		<default selectorValue="87.0" default="0"/>
