=== Fausti1971/JXG/rsc/structure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="structure">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="module" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="module">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="info" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="bulk" maxOccurs="unbounded"/>
			</xs:sequence>
		<xs:attribute name="name" use="required" type="xs:string"/>
		<xs:attribute name="address" use="required" type="moduleAddress"/>
		<xs:attribute name="translator" use="optional" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="info">
		<xs:complexType>
			<xs:attribute name="address" type="valueAddress"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="bulk">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="opcode" type="opcode" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="address" use="required" type="bulkAddress"/>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="opcode" abstract="true"/>

	<xs:complexType name="immutable">
		<xs:complexContent mixed="false">
			<xs:extension base="opcode">
				<xs:attributeGroup ref="opcodeAttribute"/>
				<xs:attributeGroup ref="actionGroup"/>
				<xs:attributeGroup ref="parameterAttribute"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="mutable">
		<xs:complexContent mixed="false">
			<xs:extension base="opcode">
				<xs:attribute name="parameterSelector" use="required" type="valueAddress"/>
				<xs:attribute name="parameters" use="required" type="xs:NCName"/>
				<xs:attributeGroup ref="opcodeAttribute"/>
				<xs:attributeGroup ref="actionGroup"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="moduleAddress">
		<xs:restriction base="xs:string">
			<xs:pattern value="([\d]+|[\d]+-[\d]+)\/([\d]+|[\d]+-[\d]+)?\/([\d]+|[\d]+-[\d]+)?"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="bulkAddress">
		<xs:restriction base="xs:string">
			<xs:pattern value="([\d]+|[\d]+-[\d]+)?\/([\d]+|[\d]+-[\d]+)?\/([\d]+|[\d]+-[\d]+)"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="valueAddress">
		<xs:restriction base="xs:string">
			<xs:pattern value="([\d]+|[\d]+-[\d]+)?\/([\d]+|[\d]+-[\d]+)?\/([\d]+)"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="opcodeAddress">
		<xs:restriction base="xs:string">
			<xs:pattern value="([\d]+|[\d]+-[\d]+)?\/([\d]+|[\d]+-[\d]+)?\/([\d]+|[\d]+-[\d]+)"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="valueType">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d+((\.\d+)+)?"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="byteTypes">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MSB"/>
			<xs:enumeration value="LSB"/>
			<xs:enumeration value="MSN"/>
			<xs:enumeration value="LSN"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string3">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="3"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string5">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="5"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:attributeGroup name="opcodeAttribute">
		<xs:attribute name="address" use="required" type="opcodeAddress"/>
		<xs:attribute name="byteType" type="byteTypes" default="LSB"/>
		<xs:attribute name="defaultSelector" use="optional" type="valueAddress"/>
		<xs:attribute name="defaults" use="optional" type="xs:NCName"/>
	</xs:attributeGroup>

	<xs:attributeGroup name="parameterAttribute">
		<xs:attribute name="name" use="required" type="xs:string"/>
		<xs:attribute name="shortName" use="optional" type="string5"/>
		<xs:attribute name="min" use="optional" type="valueType" default="0"/>
		<xs:attribute name="max" use="optional" type="valueType" default="127"/>
		<xs:attribute name="origin" use="optional" type="xs:nonNegativeInteger" default="0"/>
		<xs:attribute name="default" use="optional" type="valueType" default="0"/>
		<xs:attribute name="translator" use="optional" type="xs:string" default="normal"/>
		<xs:attribute name="tableFilter" use="optional" type="xs:string"/>
		<xs:attribute name="unit" use="optional" type="string3"/>
	</xs:attributeGroup>

	<xs:attributeGroup name="actionGroup">
		<xs:attribute name="before_edit" use="optional" type="xs:string"/>
		<xs:attribute name="after_edit" use="optional" type="xs:string"/>
		<xs:attribute name="before_send" use="optional" type="xs:string"/>
		<xs:attribute name="after_send" use="optional" type="xs:string"/>
	</xs:attributeGroup>
</xs:schema>

=== Fausti1971/JXG/src/xml/structure.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--jetzt ganz neu: fehlende min- und max-Attribute werden durch UNLIMITED (-1) ersetzt, d.h. durch die Limits der Table;
-->
<structure xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="structure.xsd">
	<virtual id="id"/>
	<virtual id="ds_progam"/>
	<module id="master" name="Master" address="0/0/0-6">
		<bulk id="master0" address="//0-6">
			<opcode xsi:type="immutable" id="master_tune" address="//0-3" byteType="LSN" name="Master Tune" shortName="Tune" min="0" max="2047" default="1024" origin="1024" table="sub1024div10" unit="cnt" actions="change"/>
			<opcode xsi:type="immutable" id="master_volume" address="//4" name="Volume" shortName="Vol" min="0" max="127" origin="0" default="100" actions="change"/>
			<opcode xsi:type="immutable" id="master_damp" address="//5" name="Attenuator" shortName="Damp" min="0" max="127" default="0" actions="change"/>
			<opcode xsi:type="immutable" id="master_transpose" address="//6" name="Transpose" shortName="Xpose" min="40" max="88" default="64" origin="64" table="sub64" unit="st" actions="change"/>
		</bulk>
	</module>

	<module id="rev" name="Reverb" address="2/1/0-21">
		<info ref="rev_program"/>
		<bulk id="rev0" address="//0-13">
			<opcode xsi:type="immutable" id="rev_program" address="//0-1" name="Reverb Program" shortName="Prog" default="1.0" table="fx_programs" tableFilter="reverb" actions="change"/>
			<opcode xsi:type="mutable" id="rev_p1" address="//2" parameterSelector="rev_program" parameterTable="fx_parameter_1" defaultSelector="rev_program" defaultsTable="fx_parameter_1" actions="change"/>
			<opcode xsi:type="mutable" id="rev_p2" address="//3" parameterSelector="rev_program" parameterTable="fx_parameter_2" defaultSelector="rev_program" defaultsTable="fx_parameter_2" actions="change"/>
			<opcode xsi:type="mutable" id="rev_p3" address="//4" parameterSelector="rev_program" parameterTable="fx_parameter_3" defaultSelector="rev_program" defaultsTable="fx_parameter_3" actions="change"/>
			<opcode xsi:type="mutable" id="rev_p4" address="//5" parameterSelector="rev_program" parameterTable="fx_parameter_4" defaultSelector="rev_program" defaultsTable="fx_parameter_4" actions="change"/>
			<opcode xsi:type="mutable" id="rev_p5" address="//6" parameterSelector="rev_program" parameterTable="fx_parameter_5" defaultSelector="rev_program" defaultsTable="fx_parameter_5" actions="change"/>
			<opcode xsi:type="mutable" id="rev_p6" address="//7" parameterSelector="rev_program" parameterTable="fx_parameter_6" defaultSelector="rev_program" defaultsTable="fx_parameter_6" actions="change"/>
			<opcode xsi:type="mutable" id="rev_p7" address="//8" parameterSelector="rev_program" parameterTable="fx_parameter_7" defaultSelector="rev_program" defaultsTable="fx_parameter_7" actions="change"/>
			<opcode xsi:type="mutable" id="rev_p8" address="//9" parameterSelector="rev_program" parameterTable="fx_parameter_8" defaultSelector="rev_program" defaultsTable="fx_parameter_8" actions="change"/>
			<opcode xsi:type="mutable" id="rev_p9" address="//10" parameterSelector="rev_program" parameterTable="fx_parameter_9" defaultSelector="rev_program" defaultsTable="fx_parameter_9" actions="change"/>
			<opcode xsi:type="mutable" id="rev_p10" address="//11" parameterSelector="rev_program" parameterTable="fx_parameter_10" defaultSelector="rev_program" defaultsTable="fx_parameter_10" actions="change"/>
			<opcode xsi:type="immutable" id="rev_return" address="//12" name="Reverb Return" default="64" min="0" max="127" shortName="FXRet" actions="change"/>
			<opcode xsi:type="immutable" id="rev_pan" address="//13" name="Reverb Panorama" shortName="FXPan" min="1" max="127" default="64" table="panorama" origin="64" actions="change"/>
		</bulk>
		<bulk id="rev16" address="//16-21">
			<opcode xsi:type="mutable" id="rev_p11" address="//16" parameterSelector="rev_program" parameterTable="fx_parameter_11" defaultSelector="rev_program" defaultsTable="fx_parameter_11" actions="change"/>
			<opcode xsi:type="mutable" id="rev_p12" address="//17" parameterSelector="rev_program" parameterTable="fx_parameter_12" defaultSelector="rev_program" defaultsTable="fx_parameter_12" actions="change"/>
			<opcode xsi:type="mutable" id="rev_p13" address="//18" parameterSelector="rev_program" parameterTable="fx_parameter_13" defaultSelector="rev_program" defaultsTable="fx_parameter_13" actions="change"/>
			<opcode xsi:type="mutable" id="rev_p14" address="//19" parameterSelector="rev_program" parameterTable="fx_parameter_14" defaultSelector="rev_program" defaultsTable="fx_parameter_14" actions="change"/>
			<opcode xsi:type="mutable" id="rev_p15" address="//20" parameterSelector="rev_program" parameterTable="fx_parameter_15" defaultSelector="rev_program" defaultsTable="fx_parameter_15" actions="change"/>
			<opcode xsi:type="mutable" id="rev_p16" address="//21" parameterSelector="rev_program" parameterTable="fx_parameter_16" defaultSelector="rev_program" defaultsTable="fx_parameter_16" actions="change"/>
		</bulk>
	</module>

	<module id="cho" name="Chorus" address="2/1/32-53">
		<info ref="cho_program"/>
		<bulk id="cho32" address="//32-46">
			<opcode xsi:type="immutable" id="cho_program" address="//32-33" name="Chorus Program" shortName="Prog" default="65.0" table="fx_programs" tableFilter="chorus" actions="change"/>
			<opcode xsi:type="mutable" id="cho_p1" address="//34" parameterSelector="cho_program" parameterTable="fx_parameter_1" defaultSelector="cho_program" defaultsTable="fx_parameter_1" actions="change"/>
			<opcode xsi:type="mutable" id="cho_p2" address="//35" parameterSelector="cho_program" parameterTable="fx_parameter_2" defaultSelector="cho_program" defaultsTable="fx_parameter_2" actions="change"/>
			<opcode xsi:type="mutable" id="cho_p3" address="//36" parameterSelector="cho_program" parameterTable="fx_parameter_3" defaultSelector="cho_program" defaultsTable="fx_parameter_3" actions="change"/>
			<opcode xsi:type="mutable" id="cho_p4" address="//37" parameterSelector="cho_program" parameterTable="fx_parameter_4" defaultSelector="cho_program" defaultsTable="fx_parameter_4" actions="change"/>
			<opcode xsi:type="mutable" id="cho_p5" address="//38" parameterSelector="cho_program" parameterTable="fx_parameter_5" defaultSelector="cho_program" defaultsTable="fx_parameter_5" actions="change"/>
			<opcode xsi:type="mutable" id="cho_p6" address="//39" parameterSelector="cho_program" parameterTable="fx_parameter_6" defaultSelector="cho_program" defaultsTable="fx_parameter_6" actions="change"/>
			<opcode xsi:type="mutable" id="cho_p7" address="//40" parameterSelector="cho_program" parameterTable="fx_parameter_7" defaultSelector="cho_program" defaultsTable="fx_parameter_7" actions="change"/>
			<opcode xsi:type="mutable" id="cho_p8" address="//41" parameterSelector="cho_program" parameterTable="fx_parameter_8" defaultSelector="cho_program" defaultsTable="fx_parameter_8" actions="change"/>
			<opcode xsi:type="mutable" id="cho_p9" address="//42" parameterSelector="cho_program" parameterTable="fx_parameter_9" defaultSelector="cho_program" defaultsTable="fx_parameter_9" actions="change"/>
			<opcode xsi:type="mutable" id="cho_p10" address="//43" parameterSelector="cho_program" parameterTable="fx_parameter_10" defaultSelector="cho_program" defaultsTable="fx_parameter_10" actions="change"/>
			<opcode xsi:type="immutable" id="cho_return" address="//44" name="Chorus Return" min="0" max="127" shortName="FXRet" actions="change"/>
			<opcode xsi:type="immutable" id="cho_pan" address="//45" name="Effect Panorama" shortName="FXPan" min="1" max="127" default="64" table="panorama" origin="64" actions="change"/>
			<opcode xsi:type="immutable" id="cho_to_rev" address="//46" name="Send To Reverb" shortName="FXRev" min="0" max="127" actions="change"/>
		</bulk>
		<bulk id="cho48" address="//48-53">
			<opcode xsi:type="mutable" id="cho_p11" address="//48" parameterSelector="cho_program" parameterTable="fx_parameter_11" defaultSelector="cho_program" defaultsTable="fx_parameter_11" actions="change"/>
			<opcode xsi:type="mutable" id="cho_p12" address="//49" parameterSelector="cho_program" parameterTable="fx_parameter_12" defaultSelector="cho_program" defaultsTable="fx_parameter_12" actions="change"/>
			<opcode xsi:type="mutable" id="cho_p13" address="//50" parameterSelector="cho_program" parameterTable="fx_parameter_13" defaultSelector="cho_program" defaultsTable="fx_parameter_13" actions="change"/>
			<opcode xsi:type="mutable" id="cho_p14" address="//51" parameterSelector="cho_program" parameterTable="fx_parameter_14" defaultSelector="cho_program" defaultsTable="fx_parameter_14" actions="change"/>
			<opcode xsi:type="mutable" id="cho_p15" address="//52" parameterSelector="cho_program" parameterTable="fx_parameter_15" defaultSelector="cho_program" defaultsTable="fx_parameter_15" actions="change"/>
			<opcode xsi:type="mutable" id="cho_p16" address="//53" parameterSelector="cho_program" parameterTable="fx_parameter_16" defaultSelector="cho_program" defaultsTable="fx_parameter_16" actions="change"/>
		</bulk>
	</module>

	<module id="var" name="Variation" address="2/1/64-117">
		<info ref="var_program"/>
		<bulk id="var64" address="//64-96">
			<opcode xsi:type="immutable" id="var_program" address="//64-65" name="Variation Program" shortName="Prog" default="5.0" table="fx_programs" tableFilter="variation" actions="change"/>
			<opcode xsi:type="mutable" id="var_p1" address="//66-67" parameterSelector="var_program" parameterTable="fx_parameter_1" defaultSelector="var_program" defaultsTable="fx_parameter_1" actions="change"/>
			<opcode xsi:type="mutable" id="var_p2" address="//68-69" parameterSelector="var_program" parameterTable="fx_parameter_2" defaultSelector="var_program" defaultsTable="fx_parameter_2" actions="change"/>
