=== Fausti1971/JXG/rsc/XGObjects.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="map">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="object" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="adressHi" type="xs:nonNegativeInteger"/>
							<xs:element name="adressMid" type="xs:nonNegativeInteger" minOccurs="0"/>
							<xs:element name="adressLo" type="xs:nonNegativeInteger" minOccurs="0"/>
							<xs:element name="parameterMap" type="xs:string"/>
							<xs:element name="dumpSequence" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="hi">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="[0-9]|[0-9]-[0-9]|[0-9],[0-9]" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="mid">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="[0-9]|[0-9]-[0-9]|[0-9],[0-9]" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="lo">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="[0-9]|[0-9]-[0-9]|[0-9],[0-9]" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="adress">
	</xs:element>
</xs:schema>

=== Fausti1971/JXG/rsc/XGObjects.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XGObjects.xsd">
	<object>
		<name>System</name>
		<adressHi>0</adressHi>
		<adressMid>0</adressMid>
		<adressLo>0</adressLo>
		<parameterMap>sys_parameters</parameterMap>
		<dumpSequence>	<!-- Separation über Komma oder Minus möglich; rekursiver loop von hi nach lo-->
			<hi>0</hi>
			<mid>0</mid>
			<lo>0</lo>
		</dumpSequence>
	</object>
	<object>
		<name>Info</name>
		<adressHi>0</adressHi>
		<adressMid>0</adressMid>
		<adressLo>0</adressLo>
		<parameterMap>info_parameters</parameterMap>
		<dumpSequence>
			<hi>1</hi>
			<mid>0</mid>
			<lo>0</lo>
		</dumpSequence>
	</object>
	<object>
		<name>FX1 Reverb</name>
		<adressHi>2</adressHi>
		<adressMid>1</adressMid>
		<adressLo>0</adressLo>hier fehlt noch was...
		<parameterMap>fx1_parameters</parameterMap>
		<dumpSequence>
			<hi>0</hi>
			<mid>0</mid>
			<lo>0</lo>
		</dumpSequence>
	</object>
</map>
