=== Fausti1971/JXG/src/xml/templates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="template" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="template">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="frame">
					<xs:attribute name="id" use="required" type="module_type"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="item" abstract="true"/>

	<xs:complexType name="frame">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
				<xs:choice>
					<xs:element name="item" type="item" maxOccurs="unbounded"/>
				</xs:choice>
				<xs:attribute name="constraint" type="constraints_type"/>
				<xs:attribute name="label" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="reset_buttons">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
				<xs:attribute name="constraint" use="required" type="constraints_type"/>
				<xs:attribute name="label" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="knob">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
				<xs:attribute name="value_tag" use="required" type="value_tag_type"/>
				<xs:attribute name="constraint" use="required" type="constraints_type"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="slider">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
				<xs:attribute name="value_tag" use="required" type="value_tag_type"/>
				<xs:attribute name="constraint" use="required" type="constraints_type"/>
				<xs:attribute name="orientation" use="optional" type="orientation_type" default="horizontal"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="range">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
				<xs:attribute name="value_tag" use="required" type="value_tag_type"/>
				<xs:attribute name="constraint" use="required" type="constraints_type"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="combo">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
				<xs:attribute name="value_tag" use="required" type="value_tag_type"/>
				<xs:attribute name="constraint" use="required" type="constraints_type"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="radio">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
				<xs:attribute name="value_tag" use="required" type="value_tag_type"/>
				<xs:attribute name="constraint" use="required" type="constraints_type"/>
				<xs:attribute name="orientation" use="optional" type="orientation_type" default="vertical"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="range_slider">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
				<xs:attribute name="value_tag" use="required" type="value_tag_type"/>
				<xs:attribute name="constraint" use="required" type="constraints_type"/>
				<xs:attribute name="orientation" use="optional" type="orientation_type" default="horizontal"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="program_selector">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
				<xs:attribute name="value_tag" use="required" type="value_tag_type"/>
				<xs:attribute name="constraint" use="required" type="constraints_type"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="flag_box">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
				<xs:attribute name="value_tag" use="required" type="value_tag_type"/>
				<xs:attribute name="label" type="xs:string"/>
				<xs:attribute name="constraint" use="required" type="constraints_type"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="checkbox">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
				<xs:attribute name="value_tag" use="required" type="value_tag_type"/>
				<xs:attribute name="label" type="xs:string"/>
				<xs:attribute name="constraint" use="required" type="constraints_type"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="velocity_envelope">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
			<xs:attribute name="constraint" use="required" type="constraints_type"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="eq_envelope">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
			<xs:attribute name="constraint" use="required" type="constraints_type"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="pitch_envelope">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
			<xs:attribute name="constraint" use="required" type="constraints_type"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="amplifier_envelope">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
			<xs:attribute name="value_tag" use="required" type="value_tag_type"/>
			<xs:attribute name="constraint" use="required" type="constraints_type"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="tab_frame">
		<xs:complexContent mixed="false">
			<xs:extension base="item">
				<xs:choice>
					<xs:element name="item" type="tab" maxOccurs="unbounded"/>
				</xs:choice>
				<xs:attribute name="constraint" type="constraints_type"/>
				<xs:attribute name="label" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="tab">
		<xs:complexContent mixed="false">
			<xs:extension base="frame">
				<xs:attribute name="title" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="module_type">
		<xs:restriction base="xs:ID">
			<xs:enumeration value="sys"/>
			<xs:enumeration value="info"/>
			<xs:enumeration value="rev"/>
			<xs:enumeration value="cho"/>
			<xs:enumeration value="var"/>
			<xs:enumeration value="eq"/>
			<xs:enumeration value="ins"/>
			<xs:enumeration value="mp"/>
			<xs:enumeration value="ad"/>
			<xs:enumeration value="ds"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="constraints_type">
		<xs:restriction base="xs:string">
			<xs:pattern value="[\d]+,[\d]+,[\d]+,[\d]+"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="orientation_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="horizontal"/>
			<xs:enumeration value="vertical"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="value_tag_type">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-z0-9,_]+"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== Fausti1971/JXG/src/xml/templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="templates.xsd">
	<template id="sys">
		<item xsi:type="knob" value_tag="master_volume" constraint="0,0,1,2"/>
		<item xsi:type="knob" value_tag="master_damp" constraint="1,0,1,2"/>
		<item xsi:type="knob" value_tag="master_transpose" constraint="2,0,1,2"/>
		<item xsi:type="knob" value_tag="master_tune"  constraint="3,0,1,2"/>
		<item xsi:type="reset_buttons" constraint="0,2,4,4"/>
	</template>

	<template id="rev" constraint="0,0,15,4">
		<item xsi:type="program_selector" value_tag="rev_program" constraint="0,0,4,1"/>
		<item xsi:type="knob" value_tag="rev_return" constraint="4,0,1,2"/>
		<item xsi:type="knob" value_tag="rev_pan" constraint="5,0,1,2"/>

		<item xsi:type="knob" value_tag="rev_p1" constraint="0,2,1,2"/>
		<item xsi:type="knob" value_tag="rev_p2" constraint="1,2,1,2"/>
		<item xsi:type="knob" value_tag="rev_p3" constraint="2,2,1,2"/>
		<item xsi:type="knob" value_tag="rev_p4" constraint="3,2,1,2"/>
		<item xsi:type="knob" value_tag="rev_p5" constraint="4,2,1,2"/>
		<item xsi:type="knob" value_tag="rev_p6" constraint="5,2,1,2"/>
		<item xsi:type="knob" value_tag="rev_p7" constraint="6,2,1,2"/>
		<item xsi:type="knob" value_tag="rev_p8" constraint="7,2,1,2"/>
		<item xsi:type="knob" value_tag="rev_p9" constraint="8,2,1,2"/>
		<item xsi:type="knob" value_tag="rev_p10" constraint="9,2,1,2"/>
		<item xsi:type="knob" value_tag="rev_p11" constraint="10,2,1,2"/>
		<item xsi:type="knob" value_tag="rev_p12" constraint="11,2,1,2"/>
		<item xsi:type="knob" value_tag="rev_p13" constraint="12,2,1,2"/>
		<item xsi:type="knob" value_tag="rev_p14" constraint="13,2,1,2"/>
		<item xsi:type="knob" value_tag="rev_p15" constraint="14,2,1,2"/>
		<item xsi:type="knob" value_tag="rev_p16" constraint="15,2,1,2"/>
	</template>

	<template id="cho" constraint="0,0,15,4">
		<item xsi:type="program_selector" value_tag="cho_program" constraint="0,0,4,1"/>
		<item xsi:type="knob" value_tag="cho_return" constraint="4,0,1,2"/>
		<item xsi:type="knob" value_tag="cho_pan" constraint="5,0,1,2"/>
		<item xsi:type="knob" value_tag="cho_to_rev" constraint="6,0,1,2"/>

		<item xsi:type="knob" value_tag="cho_p1" constraint="0,2,1,2"/>
		<item xsi:type="knob" value_tag="cho_p2" constraint="1,2,1,2"/>
		<item xsi:type="knob" value_tag="cho_p3" constraint="2,2,1,2"/>
		<item xsi:type="knob" value_tag="cho_p4" constraint="3,2,1,2"/>
		<item xsi:type="knob" value_tag="cho_p5" constraint="4,2,1,2"/>
		<item xsi:type="knob" value_tag="cho_p6" constraint="5,2,1,2"/>
		<item xsi:type="knob" value_tag="cho_p7" constraint="6,2,1,2"/>
		<item xsi:type="knob" value_tag="cho_p8" constraint="7,2,1,2"/>
		<item xsi:type="knob" value_tag="cho_p9" constraint="8,2,1,2"/>
		<item xsi:type="knob" value_tag="cho_p10" constraint="9,2,1,2"/>
		<item xsi:type="knob" value_tag="cho_p11" constraint="10,2,1,2"/>
		<item xsi:type="knob" value_tag="cho_p12" constraint="11,2,1,2"/>
		<item xsi:type="knob" value_tag="cho_p13" constraint="12,2,1,2"/>
		<item xsi:type="knob" value_tag="cho_p14" constraint="13,2,1,2"/>
		<item xsi:type="knob" value_tag="cho_p15" constraint="14,2,1,2"/>
		<item xsi:type="knob" value_tag="cho_p16" constraint="15,2,1,2"/>
	</template>

	<template id="var" constraint="0,0,15,4">
		<item xsi:type="program_selector" value_tag="var_program" constraint="0,0,4,1"/>
		<item xsi:type="knob" value_tag="var_return" constraint="4,0,1,2"/>
		<item xsi:type="knob" value_tag="var_pan" constraint="5,0,1,2"/>
		<item xsi:type="knob" value_tag="var_to_rev" constraint="6,0,1,2"/>
		<item xsi:type="knob" value_tag="var_to_cho" constraint="7,0,1,2"/>
		<item xsi:type="radio" value_tag="var_connection" constraint="0,1,2,1" orientation="horizontal"/>
		<item xsi:type="combo" value_tag="var_part" constraint="2,1,2,1"/>

		<item xsi:type="knob" value_tag="var_mw" constraint="9,0,1,2"/>
		<item xsi:type="knob" value_tag="var_pb" constraint="10,0,1,2"/>
		<item xsi:type="knob" value_tag="var_cat" constraint="11,0,1,2"/>
		<item xsi:type="knob" value_tag="var_ac1" constraint="12,0,1,2"/>
		<item xsi:type="knob" value_tag="var_ac2" constraint="13,0,1,2"/>

		<item xsi:type="knob" value_tag="var_p1" constraint="0,2,1,2"/>
		<item xsi:type="knob" value_tag="var_p2" constraint="1,2,1,2"/>
		<item xsi:type="knob" value_tag="var_p3" constraint="2,2,1,2"/>
		<item xsi:type="knob" value_tag="var_p4" constraint="3,2,1,2"/>
		<item xsi:type="knob" value_tag="var_p5" constraint="4,2,1,2"/>
		<item xsi:type="knob" value_tag="var_p6" constraint="5,2,1,2"/>
		<item xsi:type="knob" value_tag="var_p7" constraint="6,2,1,2"/>
		<item xsi:type="knob" value_tag="var_p8" constraint="7,2,1,2"/>
		<item xsi:type="knob" value_tag="var_p9" constraint="8,2,1,2"/>
		<item xsi:type="knob" value_tag="var_p10" constraint="9,2,1,2"/>
		<item xsi:type="knob" value_tag="var_p11" constraint="10,2,1,2"/>
		<item xsi:type="knob" value_tag="var_p12" constraint="11,2,1,2"/>
		<item xsi:type="knob" value_tag="var_p13" constraint="12,2,1,2"/>
		<item xsi:type="knob" value_tag="var_p14" constraint="13,2,1,2"/>
		<item xsi:type="knob" value_tag="var_p15" constraint="14,2,1,2"/>
		<item xsi:type="knob" value_tag="var_p16" constraint="15,2,1,2"/>
	</template>

	<template id="ins" constraint="0,0,15,4">
		<item xsi:type="program_selector" value_tag="ins_program" constraint="0,0,4,1"/>
		<item xsi:type="combo" value_tag="ins_part" constraint="2,1,2,1"/>

		<item xsi:type="knob" value_tag="ins_mw" constraint="9,0,1,2"/>
		<item xsi:type="knob" value_tag="ins_pb" constraint="10,0,1,2"/>
		<item xsi:type="knob" value_tag="ins_cat" constraint="11,0,1,2"/>
		<item xsi:type="knob" value_tag="ins_ac1" constraint="12,0,1,2"/>
		<item xsi:type="knob" value_tag="ins_ac2" constraint="13,0,1,2"/>
		<item xsi:type="knob" value_tag="ins_cbc1" constraint="14,0,1,2"/>
		<item xsi:type="knob" value_tag="ins_cbc2" constraint="15,0,1,2"/>


		<item xsi:type="tab_frame" label="Parameter" constraint="0,2,10,2">
			<item xsi:type="tab" constraint="0,0,10,2" label="Byte">
				<item xsi:type="knob" value_tag="ins_p1" constraint="0,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p2" constraint="1,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p3" constraint="2,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p4" constraint="3,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p5" constraint="4,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p6" constraint="5,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p7" constraint="6,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p8" constraint="7,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p9" constraint="8,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p10" constraint="9,0,1,2"/>
			</item>
			<item xsi:type="tab" constraint="0,0,10,2" label="Word">
				<item xsi:type="knob" value_tag="ins_p1w" constraint="0,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p2w" constraint="1,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p3w" constraint="2,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p4w" constraint="3,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p5w" constraint="4,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p6w" constraint="5,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p7w" constraint="6,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p8w" constraint="7,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p9w" constraint="8,0,1,2"/>
				<item xsi:type="knob" value_tag="ins_p10w" constraint="9,0,1,2"/>
			</item>
		</item>

		<item xsi:type="knob" value_tag="ins_p11" constraint="10,2,1,2"/>
		<item xsi:type="knob" value_tag="ins_p12" constraint="11,2,1,2"/>
		<item xsi:type="knob" value_tag="ins_p13" constraint="12,2,1,2"/>
		<item xsi:type="knob" value_tag="ins_p14" constraint="13,2,1,2"/>
		<item xsi:type="knob" value_tag="ins_p15" constraint="14,2,1,2"/>
		<item xsi:type="knob" value_tag="ins_p16" constraint="15,2,1,2"/>
	</template>

	<template id="eq">
		<item xsi:type="radio" constraint="0,0,5,1" value_tag="eq_program" orientation="horizontal"/>
		<item xsi:type="eq_envelope" constraint="0,1,5,4"/>

		<item xsi:type="knob" constraint="0,5,1,2" value_tag="eq_gain1"/>
		<item xsi:type="knob" constraint="0,7,1,2" value_tag="eq_freq1"/>
		<item xsi:type="knob" constraint="0,9,1,2" value_tag="eq_q1"/>
		<item xsi:type="radio" constraint="0,11,1,2" value_tag="eq_shape1" orientation="vertical"/>

		<item xsi:type="knob" constraint="1,5,1,2" value_tag="eq_gain2"/>
		<item xsi:type="knob" constraint="1,7,1,2" value_tag="eq_freq2"/>
		<item xsi:type="knob" constraint="1,9,1,2" value_tag="eq_q2"/>

		<item xsi:type="knob" constraint="2,5,1,2" value_tag="eq_gain3"/>
		<item xsi:type="knob" constraint="2,7,1,2" value_tag="eq_freq3"/>
		<item xsi:type="knob" constraint="2,9,1,2" value_tag="eq_q3"/>

		<item xsi:type="knob" constraint="3,5,1,2" value_tag="eq_gain4"/>
		<item xsi:type="knob" constraint="3,7,1,2" value_tag="eq_freq4"/>
		<item xsi:type="knob" constraint="3,9,1,2" value_tag="eq_q4"/>

		<item xsi:type="knob" constraint="4,5,1,2" value_tag="eq_gain5"/>
		<item xsi:type="knob" constraint="4,7,1,2" value_tag="eq_freq5"/>
		<item xsi:type="knob" constraint="4,9,1,2" value_tag="eq_q5"/>
		<item xsi:type="radio" constraint="4,11,1,2" value_tag="eq_shape5" orientation="vertical"/>
	</template>

	<template id="mp">
		<item xsi:type="program_selector" value_tag="mp_program" constraint="0,0,4,1"/>
		<item xsi:type="combo" value_tag="mp_partmode" constraint="4,0,2,1"/>
		<item xsi:type="combo" value_tag="mp_midi_channel" constraint="6,0,2,1"/>
		<item xsi:type="flag_box" label="MIDI Filter" value_tag="mp_rcv_pb,mp_rcv_cat,mp_rcv_prg,mp_rcv_cc,mp_rcv_pat,mp_rcv_note,mp_rcv_rpn,mp_rcv_nrpn,mp_rcv_mw,mp_rcv_vol,mp_rcv_pan,mp_rcv_exp,mp_rcv_hold,mp_rcv_portamento,mp_rcv_sostenuto,mp_rcv_softpedal,mp_rcv_bank" constraint="8,0,2,1"/>
