=== Fausti1971/JXG/xml/xsd/template.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="frame" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="frame">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="frame" maxOccurs="unbounded"/>
				<xs:element ref="tabs" maxOccurs="unbounded"/>
				<xs:element ref="knob" maxOccurs="unbounded"/>
				<xs:element ref="slider" maxOccurs="unbounded"/>
				<xs:element ref="range" maxOccurs="unbounded"/>
				<xs:element ref="combo" maxOccurs="unbounded"/>
				<xs:element ref="radio" maxOccurs="unbounded"/>
				<xs:element ref="button" maxOccurs="unbounded"/>
				<xs:element ref="selector" maxOccurs="unbounded"/>
				<xs:element ref="aeg" maxOccurs="unbounded"/>
				<xs:element ref="peg" maxOccurs="unbounded"/>
				<xs:element ref="veg" maxOccurs="unbounded"/>
				<xs:element ref="meq" maxOccurs="unbounded"/>
				<xs:element ref="flagbox" maxOccurs="unbounded"/>
				<xs:element ref="scale" maxOccurs="unbounded"/>
				<xs:element ref="keyboard" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attributeGroup ref="layoutGroup"/>
			<xs:attribute name="address" use="optional" type="addressType"/>
			<xs:attribute name="name" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="tabs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="frame" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="knob">
		<xs:complexType>
			<xs:attributeGroup ref="layoutGroup"/>
			<xs:attribute name="address" use="required" type="addressType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="slider">
		<xs:complexType>
			<xs:attributeGroup ref="layoutGroup"/>
			<xs:attribute name="address" use="required" type="addressType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="range">
		<xs:complexType>
			<xs:attributeGroup ref="layoutGroup"/>
			<xs:attribute name="address_lo" use="required" type="addressType"/>
			<xs:attribute name="address_hi" use="required" type="addressType"/>
			<xs:attribute name="name" use="optional" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="combo">
		<xs:complexType>
			<xs:attributeGroup ref="layoutGroup"/>
			<xs:attribute name="address" use="required" type="addressType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="radio">
		<xs:complexType>
			<xs:attributeGroup ref="layoutGroup"/>
			<xs:attribute name="address" use="required" type="addressType"/>
			<xs:attribute name="orientation" use="optional" type="orientationType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="veg">
		<xs:complexType>
			<xs:attributeGroup ref="layoutGroup"/>
			<xs:attributeGroup ref="panelGroup"/>
			<xs:attribute name="name" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="aeg">
		<xs:complexType>
			<xs:attributeGroup ref="layoutGroup"/>
			<xs:attributeGroup ref="panelGroup"/>
			<xs:attribute name="name" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="peg">
		<xs:complexType>
			<xs:attributeGroup ref="layoutGroup"/>
			<xs:attributeGroup ref="panelGroup"/>
			<xs:attribute name="name" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="meq">
		<xs:complexType>
			<xs:attributeGroup ref="layoutGroup"/>
			<xs:attributeGroup ref="panelGroup"/>
			<xs:attribute name="name" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="button">
		<xs:complexType>
			<xs:attributeGroup ref="layoutGroup"/>
			<xs:attribute name="address" use="required" type="addressType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="selector">
		<xs:complexType>
			<xs:attributeGroup ref="layoutGroup"/>
			<xs:attribute name="address" use="required" type="addressType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="flagbox">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="flag" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attributeGroup ref="layoutGroup"/>
			<xs:attribute name="name"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="flag">
		<xs:complexType>
			<xs:attribute name="address" use="required" type="addressType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="scale">
		<xs:complexType>
			<xs:attributeGroup ref="layoutGroup"/>
			<xs:attributeGroup ref="panelGroup"/>
			<xs:attribute name="name" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="keyboard">
		<xs:complexType>
			<xs:attributeGroup ref="layoutGroup"/>
			<xs:attribute name="name" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:attributeGroup name="layoutGroup">
		<xs:attribute name="bounds" use="required" type="boundType"/>
	</xs:attributeGroup>

	<xs:attributeGroup name="panelGroup">
		<xs:attribute name="grid_x" type="xs:nonNegativeInteger" use="optional"/>
		<xs:attribute name="grid_y" type="xs:nonNegativeInteger" use="optional"/>
		<xs:attribute name="origin_x" type="xs:nonNegativeInteger" use="optional"/>
		<xs:attribute name="origin_y" type="xs:nonNegativeInteger" use="optional"/>
	</xs:attributeGroup>

	<xs:simpleType name="boundType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[\d]+,[\d]+,[\d]+,[\d]+"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="addressType">
		<xs:restriction base="xs:string">
			<xs:pattern value="([\d]+|[\d]+-[\d]+)?\/([\d]+|[\d]+-[\d]+)?\/([\d]+|[\d]+-[\d]+)?"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="orientationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="horizontal"/>
			<xs:enumeration value="vertical"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Fausti1971/JXG/xml/XG/template.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../xsd/template.xsd">
	<frame address="0/0/" bounds="0,0,0,0">
		<knob address="0/0/0" bounds="0,0,3,4"/>
		<knob address="0/0/4" bounds="3,0,3,4"/>
		<knob address="0/0/5" bounds="6,0,3,4"/>
		<knob address="0/0/6" bounds="9,0,3,4"/>
	</frame>
	<frame address="2/1/0-21" bounds="0,0,0,0">
		<selector address="2/1/0" bounds="0,0,15,2"/>
		<knob address="2/1/12" bounds="15,0,3,4"/>
		<knob address="2/1/13" bounds="18,0,3,4"/>

		<knob address="2/1/2" bounds="0,4,3,4"/>
		<knob address="2/1/3" bounds="3,4,3,4"/>
		<knob address="2/1/4" bounds="6,4,3,4"/>
		<knob address="2/1/5" bounds="9,4,3,4"/>
		<knob address="2/1/6" bounds="12,4,3,4"/>
		<knob address="2/1/7" bounds="15,4,3,4"/>
		<knob address="2/1/8" bounds="18,4,3,4"/>
		<knob address="2/1/9" bounds="21,4,3,4"/>
		<knob address="2/1/10" bounds="24,4,3,4"/>
		<knob address="2/1/11" bounds="27,4,3,4"/>
		<knob address="2/1/16" bounds="30,4,3,4"/>
		<knob address="2/1/17" bounds="33,4,3,4"/>
		<knob address="2/1/18" bounds="36,4,3,4"/>
		<knob address="2/1/19" bounds="39,4,3,4"/>
		<knob address="2/1/20" bounds="42,4,3,4"/>
		<knob address="2/1/21" bounds="45,4,3,4"/>
	</frame>

	<frame address="2/1/32-53" bounds="0,0,0,0">
		<selector address="2/1/32" bounds="0,0,15,2"/>
		<knob address="2/1/44" bounds="15,0,3,4"/>
		<knob address="2/1/45" bounds="18,0,3,4"/>
		<knob address="2/1/46" bounds="21,0,3,4"/>

		<knob address="2/1/34" bounds="0,4,3,4"/>
		<knob address="2/1/35" bounds="3,4,3,4"/>
		<knob address="2/1/36" bounds="6,4,3,4"/>
		<knob address="2/1/37" bounds="9,4,3,4"/>
		<knob address="2/1/38" bounds="12,4,3,4"/>
		<knob address="2/1/39" bounds="15,4,3,4"/>
		<knob address="2/1/40" bounds="18,4,3,4"/>
		<knob address="2/1/41" bounds="21,4,3,4"/>
		<knob address="2/1/42" bounds="24,4,3,4"/>
		<knob address="2/1/43" bounds="27,4,3,4"/>
		<knob address="2/1/48" bounds="30,4,3,4"/>
		<knob address="2/1/49" bounds="33,4,3,4"/>
		<knob address="2/1/50" bounds="36,4,3,4"/>
		<knob address="2/1/51" bounds="39,4,3,4"/>
		<knob address="2/1/52" bounds="42,4,3,4"/>
		<knob address="2/1/53" bounds="45,4,3,4"/>
	</frame>

	<frame address="2/1/64-117"  bounds="0,0,0,0">
		<selector address="2/1/64" bounds="0,0,15,2"/>
		<knob address="2/1/86" bounds="15,0,3,4"/>
		<knob address="2/1/87" bounds="18,0,3,4"/>
		<knob address="2/1/88" bounds="21,0,3,4"/>
		<knob address="2/1/89" bounds="24,0,3,4"/>
		<radio address="2/1/90" bounds="27,0,5,4" orientation="vertical"/>
		<knob address="2/1/91" bounds="32,0,3,4"/>

		<knob address="2/1/92" bounds="0,4,3,4"/>
		<knob address="2/1/93" bounds="3,4,3,4"/>
		<knob address="2/1/94" bounds="6,4,3,4"/>
		<knob address="2/1/95" bounds="9,4,3,4"/>
		<knob address="2/1/96" bounds="12,4,3,4"/>
		<knob address="2/1/97" bounds="15,4,3,4"/>
		<knob address="2/1/98" bounds="18,4,3,4"/>

		<knob address="2/1/66" bounds="0,8,3,4"/>
		<knob address="2/1/68" bounds="3,8,3,4"/>
		<knob address="2/1/70" bounds="6,8,3,4"/>
		<knob address="2/1/72" bounds="9,8,3,4"/>
		<knob address="2/1/74" bounds="12,8,3,4"/>
		<knob address="2/1/76" bounds="15,8,3,4"/>
		<knob address="2/1/78" bounds="18,8,3,4"/>
		<knob address="2/1/80" bounds="21,8,3,4"/>
		<knob address="2/1/82" bounds="24,8,3,4"/>
		<knob address="2/1/84" bounds="27,8,3,4"/>
		<knob address="2/1/112" bounds="30,8,3,4"/>
		<knob address="2/1/113" bounds="33,8,3,4"/>
		<knob address="2/1/114" bounds="36,8,3,4"/>
		<knob address="2/1/115" bounds="39,8,3,4"/>
		<knob address="2/1/116" bounds="42,8,3,4"/>
		<knob address="2/1/117" bounds="45,8,3,4"/>
	</frame>
	<frame address="3//" bounds="0,0,0,0">
		<selector address="3//0" bounds="0,0,15,2"/>
		<knob address="3//12" bounds="15,0,3,4"/>

		<knob address="3//13" bounds="0,4,3,4"/>
		<knob address="3//14" bounds="3,4,3,4"/>
		<knob address="3//15" bounds="6,4,3,4"/>
		<knob address="3//16" bounds="9,4,3,4"/>
		<knob address="3//17" bounds="12,4,3,4"/>
		<knob address="3//18" bounds="15,4,3,4"/>
		<knob address="3//19" bounds="18,4,3,4"/>

		<knob address="3//2" bounds="0,8,3,4"/>
		<knob address="3//3" bounds="3,8,3,4"/>
		<knob address="3//4" bounds="6,8,3,4"/>
		<knob address="3//5" bounds="9,8,3,4"/>
		<knob address="3//6" bounds="12,8,3,4"/>
		<knob address="3//7" bounds="15,8,3,4"/>
		<knob address="3//8" bounds="18,8,3,4"/>
		<knob address="3//9" bounds="21,8,3,4"/>
		<knob address="3//10" bounds="24,8,3,4"/>
		<knob address="3//11" bounds="27,8,3,4"/>
		<knob address="3//32" bounds="30,8,3,4"/>
		<knob address="3//33" bounds="33,8,3,4"/>
		<knob address="3//34" bounds="36,8,3,4"/>
		<knob address="3//35" bounds="39,8,3,4"/>
		<knob address="3//36" bounds="42,8,3,4"/>
		<knob address="3//37" bounds="45,8,3,4"/>
	</frame>

	<frame name="Multi EQ" bounds="0,0,0,0" address="2/64/">
		<radio bounds="0,0,15,2" address="//0" orientation="horizontal"/>

		<meq name="Graphic" bounds="0,2,15,6" grid_x="3" grid_y="5" origin_y="64"/>

		<knob bounds="0,8,3,4" address="//1"/>
		<knob bounds="0,12,3,4" address="//2"/>
		<knob bounds="0,16,3,4" address="//3"/>
		<radio bounds="0,20,3,3" address="//4" orientation="vertical"/>

		<knob bounds="3,8,3,4" address="//5"/>
		<knob bounds="3,12,3,4" address="//6"/>
		<knob bounds="3,16,3,4" address="//7"/>

		<knob bounds="6,8,3,4" address="//9"/>
		<knob bounds="6,12,3,4" address="//10"/>
		<knob bounds="6,16,3,4" address="//11"/>

		<knob bounds="9,8,3,4" address="//13"/>
		<knob bounds="9,12,3,4" address="//14"/>
		<knob bounds="9,16,3,4" address="//15"/>

		<knob bounds="12,8,3,4" address="//17"/>
		<knob bounds="12,12,3,4" address="//18"/>
		<knob bounds="12,16,3,4" address="//19"/>
		<radio bounds="12,20,3,3" address="//20" orientation="vertical"/>
	</frame>

	<frame address="8-10//" bounds="0,0,0,0">
		<frame address="8-10//" name="Midi" bounds="0,0,0,0">
			<knob address="8//4" bounds="0,0,3,4"/>
			<flagbox name="Receiving Flags..." bounds="3,2,9,2">
				<flag address="8//48"/>
				<flag address="8//49"/>
				<flag address="8//50"/>
				<flag address="8//51"/>
				<flag address="8//52"/>
				<flag address="8//53"/>
				<flag address="8//54"/>
				<flag address="8//55"/>
				<flag address="8//56"/>
				<flag address="8//57"/>
				<flag address="8//58"/>
				<flag address="8//59"/>
				<flag address="8//60"/>
				<flag address="8//61"/>
				<flag address="8//62"/>
				<flag address="8//63"/>
				<flag address="8//64"/>
			</flagbox>
			<range name="Note Limit" address_lo="8//15" address_hi="8//16" bounds="0,4,12,2"/>
			<veg name="Velocity" bounds="12,0,12,6" grid_x="1" grid_y="1" origin_y="64"/>
			<keyboard name="Play" bounds="24,0,12,6"/>
		</frame>
		<frame address="8-10//" name="Voice" bounds="0,7,0,0">
			<combo address="8//7" bounds="0,0,6,2"/>
			<selector address="8//1" bounds="6,0,15,2"/>
			<combo address="8//5" bounds="21,0,5,2"/>
			<combo address="8//6" bounds="26,0,5,2"/>
			<combo address="10//16" bounds="31,0,5,2"/>

			<knob address="8//11" bounds="0,2,3,4"/>
			<knob address="8//14" bounds="3,2,3,4"/>
			<knob address="8//8" bounds="6,2,3,4"/>
			<knob address="8//9" bounds="9,2,3,4"/>
			<knob address="8//0" bounds="12,2,3,4"/>

			<knob address="8//21" bounds="18,2,3,4"/>
			<knob address="8//22" bounds="21,2,3,4"/>
			<knob address="8//23" bounds="24,2,3,4"/>

			<radio address="8//103" bounds="30,2,3,4" orientation="vertical"/>
			<knob address="8//104" bounds="33,2,3,4"/>

			<knob address="8//17" bounds="0,6,3,4"/>
			<knob address="8//19" bounds="3,6,3,4"/>
			<knob address="8//18" bounds="6,6,3,4"/>
			<knob address="8//20" bounds="9,6,3,4"/>

			<knob address="10//32" bounds="12,6,3,4"/>
			<knob address="8//24" bounds="15,6,3,4"/>
			<knob address="8//25" bounds="18,6,3,4"/>
			<knob address="8//113" bounds="21,6,3,4"/>

			<knob address="8//118" bounds="24,6,3,4"/>
			<knob address="8//114" bounds="27,6,3,4"/>
			<knob address="8//119" bounds="30,6,3,4"/>
			<knob address="8//115" bounds="33,6,3,4"/>

			<aeg name="Amplitude Envelope" bounds="0,10,12,6" grid_x="1" grid_y="5"/>
			<peg name="Pitch Envelope" bounds="12,10,12,6" grid_x="1" grid_y="5" origin_y="64"/>
			<scale name="Scale Tuning" bounds="24,10,12,6" grid_x="1" origin_y="64"/>
		</frame>
		<frame address="8-10//" name="Control" bounds="0,24,0,0">
			<tabs>
				<frame name="MW" bounds="0,0,0,0">
					<knob address="8//29" bounds="3,0,3,4"/>
					<knob address="8//30" bounds="6,0,3,4"/>
					<knob address="10//34" bounds="9,0,3,4"/>
					<knob address="8//31" bounds="12,0,3,4"/>
					<knob address="8//32" bounds="15,0,3,4"/>
					<knob address="8//33" bounds="18,0,3,4"/>
					<knob address="8//34" bounds="21,0,3,4"/>
					<knob address="10//64" bounds="24,0,3,4"/>
				</frame>
				<frame name="PBW" bounds="0,0,0,0">
					<knob address="8//35" bounds="3,0,3,4"/>
					<knob address="8//36" bounds="6,0,3,4"/>
					<knob address="10//35" bounds="9,0,3,4"/>
					<knob address="8//37" bounds="12,0,3,4"/>
					<knob address="8//38" bounds="15,0,3,4"/>
					<knob address="8//39" bounds="18,0,3,4"/>
					<knob address="8//40" bounds="21,0,3,4"/>
					<knob address="10//65" bounds="24,0,3,4"/>
					<knob address="8//112" bounds="27,0,3,4"/>
				</frame>
				<frame name="CAT" bounds="0,0,0,0">
					<knob address="8//77" bounds="3,0,3,4"/>
					<knob address="8//78" bounds="6,0,3,4"/>
					<knob address="10//36" bounds="9,0,3,4"/>
					<knob address="8//79" bounds="12,0,3,4"/>
					<knob address="8//80" bounds="15,0,3,4"/>
					<knob address="8//81" bounds="18,0,3,4"/>
					<knob address="8//82" bounds="21,0,3,4"/>
					<knob address="10//66" bounds="24,0,3,4"/>
				</frame>
				<frame name="PAT" bounds="0,0,0,0">
					<knob address="8//83" bounds="3,0,3,4"/>
					<knob address="8//84" bounds="6,0,3,4"/>
					<knob address="10//37" bounds="9,0,3,4"/>
					<knob address="8//85" bounds="12,0,3,4"/>
					<knob address="8//86" bounds="15,0,3,4"/>
					<knob address="8//87" bounds="18,0,3,4"/>
