=== Fausti1971/JXG/src/rsc/XG/defaults.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="defaultsTables">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="defaultsTable" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="defaultsTable">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="item" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="id" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
		<xs:attribute name="name" use="required" type="xs:NCName"/>
		<xs:attribute name="range" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="id">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="item" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		<xs:attribute name="value" use="required" type="valueType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="item">
		<xs:complexType>
			<xs:attribute name="selectorValue" type="valueType" use="required"/>
			<xs:attribute name="value" type="valueType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="valueType">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d+((\.\d+)+)?"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Fausti1971/JXG/src/xml/defaults.xml
<?xml version="1.0" encoding="UTF-8"?>
<defaultsTables xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="defaults.xsd">
	<defaultsTable name="fx_parameter_1">
		<item selectorValue="118.0" defaultValue="80"/>
		<item selectorValue="7.0" defaultValue="1700"/>
		<item selectorValue="102.0" defaultValue="11"/>
		<item selectorValue="88.0" defaultValue="114"/>
		<item selectorValue="127.2" defaultValue="64"/>
		<item selectorValue="2.0" defaultValue="5"/>
		<item selectorValue="92.0" defaultValue="0"/>
		<item selectorValue="73.8" defaultValue="18"/>
		<item selectorValue="20.0" defaultValue="63"/>
		<item selectorValue="2.6" defaultValue="13"/>
		<item selectorValue="1.2" defaultValue="18"/>
		<item selectorValue="66.1" defaultValue="28"/>
		<item selectorValue="2.7" defaultValue="15"/>
		<item selectorValue="67.7" defaultValue="3"/>
		<item selectorValue="95.0" defaultValue="2500"/>
		<item selectorValue="21.8" defaultValue="11"/>
		<item selectorValue="114.0" defaultValue="5"/>
		<item selectorValue="67.8" defaultValue="4"/>
		<item selectorValue="80.1" defaultValue="65"/>
		<item selectorValue="4.7" defaultValue="13"/>
		<item selectorValue="82.0" defaultValue="36"/>
		<item selectorValue="65.3" defaultValue="9"/>
		<item selectorValue="5.0" defaultValue="3333"/>
		<item selectorValue="86.2" defaultValue="5"/>
		<item selectorValue="9.0" defaultValue="0"/>
		<item selectorValue="105.0" defaultValue="9"/>
		<item selectorValue="67.1" defaultValue="32"/>
		<item selectorValue="81.0" defaultValue="44"/>
		<item selectorValue="98.2" defaultValue="13"/>
		<item selectorValue="91.0" defaultValue="0"/>
		<item selectorValue="127.3" defaultValue="89"/>
		<item selectorValue="73.1" defaultValue="40"/>
		<item selectorValue="93.0" defaultValue="0"/>
		<item selectorValue="107.0" defaultValue="17"/>
		<item selectorValue="101.0" defaultValue="11"/>
		<item selectorValue="69.2" defaultValue="7"/>
		<item selectorValue="20.2" defaultValue="43"/>
		<item selectorValue="72.0" defaultValue="8"/>
		<item selectorValue="100.1" defaultValue="11"/>
		<item selectorValue="75.8" defaultValue="16"/>
		<item selectorValue="101.1" defaultValue="11"/>
		<item selectorValue="68.0" defaultValue="12"/>
		<item selectorValue="71.1" defaultValue="67"/>
		<item selectorValue="108.0" defaultValue="17"/>
		<item selectorValue="116.0" defaultValue="3"/>
		<item selectorValue="78.2" defaultValue="48"/>
		<item selectorValue="4.1" defaultValue="23"/>
		<item selectorValue="2.4" defaultValue="5"/>
		<item selectorValue="96.1" defaultValue="3000"/>
		<item selectorValue="65.2" defaultValue="4"/>
		<item selectorValue="2.5" defaultValue="11"/>
		<item selectorValue="69.3" defaultValue="5"/>
		<item selectorValue="2.3" defaultValue="3"/>
		<item selectorValue="65.1" defaultValue="8"/>
		<item selectorValue="1.1" defaultValue="25"/>
		<item selectorValue="80.0" defaultValue="64"/>
		<item selectorValue="9.1" defaultValue="2"/>
		<item selectorValue="127.1" defaultValue="64"/>
		<item selectorValue="97.0" defaultValue="1600"/>
		<item selectorValue="82.1" defaultValue="36"/>
		<item selectorValue="109.0" defaultValue="1"/>
		<item selectorValue="84.0" defaultValue="0"/>
		<item selectorValue="6.0" defaultValue="2500"/>
		<item selectorValue="69.0" defaultValue="81"/>
		<item selectorValue="77.0" defaultValue="28"/>
		<item selectorValue="82.2" defaultValue="45"/>
		<item selectorValue="103.1" defaultValue="14"/>
		<item selectorValue="86.3" defaultValue="8"/>
		<item selectorValue="119.0" defaultValue="69"/>
		<item selectorValue="65.4" defaultValue="26"/>
		<item selectorValue="104.0" defaultValue="5"/>
		<item selectorValue="66.8" defaultValue="8"/>
		<item selectorValue="75.0" defaultValue="39"/>
		<item selectorValue="2.2" defaultValue="9"/>
		<item selectorValue="115.0" defaultValue="1"/>
		<item selectorValue="21.0" defaultValue="10"/>
		<item selectorValue="66.2" defaultValue="4"/>
		<item selectorValue="3.1" defaultValue="11"/>
		<item selectorValue="111.0" defaultValue="98"/>
		<item selectorValue="1.7" defaultValue="18"/>
		<item selectorValue="22.0" defaultValue="8"/>
		<item selectorValue="102.1" defaultValue="11"/>
		<item selectorValue="66.0" defaultValue="12"/>
		<item selectorValue="103.0" defaultValue="22"/>
		<item selectorValue="86.0" defaultValue="16"/>
		<item selectorValue="69.1" defaultValue="6"/>
		<item selectorValue="1.6" defaultValue="18"/>
		<item selectorValue="3.0" defaultValue="19"/>
		<item selectorValue="65.8" defaultValue="9"/>
		<item selectorValue="4.0" defaultValue="25"/>
		<item selectorValue="78.0" defaultValue="70"/>
		<item selectorValue="99.0" defaultValue="15"/>
		<item selectorValue="95.1" defaultValue="1900"/>
		<item selectorValue="96.0" defaultValue="3000"/>
		<item selectorValue="82.8" defaultValue="68"/>
		<item selectorValue="65.0" defaultValue="6"/>
		<item selectorValue="65.7" defaultValue="6"/>
		<item selectorValue="76.0" defaultValue="70"/>
		<item selectorValue="94.0" defaultValue="2"/>
		<item selectorValue="10.0" defaultValue="0"/>
		<item selectorValue="90.0" defaultValue="0"/>
		<item selectorValue="70.0" defaultValue="83"/>
		<item selectorValue="17.0" defaultValue="48"/>
		<item selectorValue="100.0" defaultValue="11"/>
		<item selectorValue="97.1" defaultValue="1600"/>
		<item selectorValue="71.0" defaultValue="76"/>
		<item selectorValue="11.0" defaultValue="1"/>
		<item selectorValue="78.1" defaultValue="40"/>
		<item selectorValue="20.1" defaultValue="55"/>
		<item selectorValue="83.0" defaultValue="6"/>
		<item selectorValue="110.0" defaultValue="122"/>
		<item selectorValue="98.0" defaultValue="22"/>
		<item selectorValue="112.0" defaultValue="70"/>
		<item selectorValue="74.8" defaultValue="10"/>
		<item selectorValue="72.8" defaultValue="8"/>
		<item selectorValue="86.1" defaultValue="6"/>
		<item selectorValue="2.1" defaultValue="12"/>
		<item selectorValue="65.5" defaultValue="9"/>
		<item selectorValue="1.0" defaultValue="18"/>
		<item selectorValue="19.0" defaultValue="3"/>
		<item selectorValue="117.0" defaultValue="1"/>
		<item selectorValue="18.0" defaultValue="59"/>
		<item selectorValue="67.0" defaultValue="14"/>
		<item selectorValue="1.3" defaultValue="15"/>
		<item selectorValue="16.0" defaultValue="9"/>
		<item selectorValue="98.3" defaultValue="14"/>
		<item selectorValue="75.1" defaultValue="50"/>
		<item selectorValue="87.0" defaultValue="54"/>
		<item selectorValue="74.0" defaultValue="29"/>
		<item selectorValue="65.6" defaultValue="26"/>
		<item selectorValue="113.0" defaultValue="98"/>
		<item selectorValue="73.0" defaultValue="40"/>
		<item selectorValue="99.1" defaultValue="14"/>
		<item selectorValue="89.0" defaultValue="0"/>
		<item selectorValue="8.0" defaultValue="1700"/>
		<item selectorValue="98.1" defaultValue="22"/>
	</defaultsTable>
	<defaultsTable name="fx_parameter_2">
		<item selectorValue="65.0" defaultValue="54"/>
		<item selectorValue="20.2" defaultValue="110"/>
		<item selectorValue="69.3" defaultValue="90"/>
		<item selectorValue="78.2" defaultValue="64"/>
		<item selectorValue="69.1" defaultValue="92"/>
		<item selectorValue="93.0" defaultValue="15"/>
		<item selectorValue="65.5" defaultValue="34"/>
		<item selectorValue="103.0" defaultValue="3"/>
		<item selectorValue="8.0" defaultValue="1750"/>
		<item selectorValue="6.0" defaultValue="3750"/>
		<item selectorValue="9.1" defaultValue="7"/>
		<item selectorValue="74.0" defaultValue="24"/>
		<item selectorValue="71.1" defaultValue="127"/>
		<item selectorValue="67.0" defaultValue="14"/>
		<item selectorValue="112.0" defaultValue="0"/>
		<item selectorValue="19.0" defaultValue="6"/>
		<item selectorValue="94.0" defaultValue="60"/>
		<item selectorValue="86.0" defaultValue="26"/>
		<item selectorValue="115.0" defaultValue="64"/>
		<item selectorValue="86.1" defaultValue="28"/>
		<item selectorValue="88.0" defaultValue="0"/>
		<item selectorValue="72.0" defaultValue="111"/>
		<item selectorValue="80.0" defaultValue="0"/>
		<item selectorValue="20.1" defaultValue="105"/>
		<item selectorValue="20.0" defaultValue="97"/>
		<item selectorValue="70.0" defaultValue="56"/>
		<item selectorValue="108.0" defaultValue="48"/>
		<item selectorValue="98.0" defaultValue="3"/>
		<item selectorValue="16.0" defaultValue="5"/>
		<item selectorValue="78.0" defaultValue="56"/>
		<item selectorValue="65.6" defaultValue="29"/>
		<item selectorValue="73.1" defaultValue="20"/>
		<item selectorValue="82.1" defaultValue="0"/>
		<item selectorValue="98.2" defaultValue="3"/>
		<item selectorValue="82.8" defaultValue="18"/>
		<item selectorValue="113.0" defaultValue="0"/>
		<item selectorValue="102.1" defaultValue="84"/>
		<item selectorValue="1.2" defaultValue="10"/>
		<item selectorValue="22.0" defaultValue="8"/>
		<item selectorValue="73.0" defaultValue="20"/>
		<item selectorValue="75.1" defaultValue="3"/>
		<item selectorValue="107.0" defaultValue="10"/>
		<item selectorValue="96.1" defaultValue="72"/>
		<item selectorValue="71.0" defaultValue="80"/>
		<item selectorValue="110.0" defaultValue="1"/>
		<item selectorValue="1.7" defaultValue="10"/>
		<item selectorValue="86.2" defaultValue="28"/>
		<item selectorValue="80.1" defaultValue="50"/>
		<item selectorValue="99.1" defaultValue="18"/>
		<item selectorValue="66.0" defaultValue="32"/>
		<item selectorValue="10.0" defaultValue="15"/>
		<item selectorValue="65.8" defaultValue="32"/>
		<item selectorValue="103.1" defaultValue="3"/>
		<item selectorValue="75.0" defaultValue="1"/>
		<item selectorValue="95.0" defaultValue="3000"/>
		<item selectorValue="118.0" defaultValue="1800"/>
		<item selectorValue="99.0" defaultValue="18"/>
		<item selectorValue="1.6" defaultValue="10"/>
		<item selectorValue="68.0" defaultValue="25"/>
		<item selectorValue="76.0" defaultValue="34"/>
		<item selectorValue="1.0" defaultValue="10"/>
		<item selectorValue="2.6" defaultValue="10"/>
		<item selectorValue="3.0" defaultValue="10"/>
