=== Fausti1971/JXG/src/rsc/XG/drums.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="drums">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="key" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="key">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="item" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		<xs:attribute name="value" use="required" type="keyNumbers"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="item">
		<xs:complexType>
			<xs:attribute name="selectorValue" type="valueType" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

   <xs:simpleType name="keyNumbers">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="13"/>
			<xs:maxInclusive value="91"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="valueType">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d+((\.\d+)+)?"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Fausti1971/JXG/src/xml/drums.xml
<?xml version="1.0" encoding="UTF-8"?>
<drums xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="drums.xsd">
	<key value="13">
		<item selectorValue="127.0.31" name="Surdo Mute V"/>
		<item selectorValue="127.0.30" name="Surdo Mute V"/>
		<item selectorValue="127.0.29" name="Surdo Mute V"/>
		<item selectorValue="127.0.28" name="Surdo Mute V"/>
		<item selectorValue="127.0.26" name="Surdo Mute V"/>
		<item selectorValue="127.0.17" name="Surdo Mute V"/>
		<item selectorValue="127.0.9" name="Surdo Mute V"/>
		<item selectorValue="127.0.7" name="Surdo Mute V"/>
		<item selectorValue="127.0.6" name="Surdo Mute V"/>
		<item selectorValue="127.0.5" name="Surdo Mute V"/>
		<item selectorValue="127.0.4" name="Surdo Mute V"/>
		<item selectorValue="127.0.3" name="Surdo Mute B"/>
		<item selectorValue="127.0.2" name="Surdo Mute V"/>
		<item selectorValue="127.0.66" name="Surdo Mute V"/>
		<item selectorValue="127.0.33" name="Surdo Mute V"/>
		<item selectorValue="127.0.65" name="Surdo Mute V"/>
		<item selectorValue="127.0.0" name="Surdo Mute"/>
	</key>
	<key value="14">
		<item selectorValue="127.0.31" name="Surdo Open V"/>
		<item selectorValue="127.0.30" name="Surdo Open V"/>
		<item selectorValue="127.0.29" name="Surdo Open V"/>
		<item selectorValue="127.0.28" name="Surdo Open V"/>
		<item selectorValue="127.0.26" name="Surdo Open V"/>
		<item selectorValue="127.0.17" name="Surdo Open V"/>
		<item selectorValue="127.0.9" name="Surdo Open V"/>
		<item selectorValue="127.0.7" name="Surdo Open V"/>
		<item selectorValue="127.0.6" name="Surdo Open V"/>
		<item selectorValue="127.0.5" name="Surdo Open V"/>
		<item selectorValue="127.0.4" name="Surdo Open V"/>
		<item selectorValue="127.0.3" name="Surdo Open B"/>
		<item selectorValue="127.0.2" name="Surdo Open V"/>
		<item selectorValue="127.0.66" name="Surdo Open V"/>
		<item selectorValue="127.0.33" name="Surdo Open V"/>
		<item selectorValue="127.0.65" name="Surdo Open V"/>
		<item selectorValue="127.0.0" name="Surdo Open"/>
	</key>
	<key value="15">
		<item selectorValue="126.0.43" name="Log Drum H Stereo"/>
		<item selectorValue="126.0.41" name="Quinto Tip Stereo"/>
		<item selectorValue="127.0.3" name="Hi Q B"/>
		<item selectorValue="127.0.0" name="Hi Q"/>
	</key>
	<key value="16">
		<item selectorValue="126.0.43" name="Log Drum L Stereo"/>
		<item selectorValue="126.0.41" name="Quinto Heel Stereo"/>
		<item selectorValue="127.0.3" name="Whip Slap B"/>
		<item selectorValue="127.0.0" name="Whip Slap"/>
	</key>
	<key value="17">
		<item selectorValue="126.0.43" name="Caxixi Stereo"/>
		<item selectorValue="126.0.41" name="Quinto Open Stereo"/>
		<item selectorValue="127.0.3" name="Scratch H B"/>
		<item selectorValue="127.0.0" name="Scratch H"/>
	</key>
	<key value="18">
		<item selectorValue="126.0.43" name="Hand Clap 1 Stereo"/>
		<item selectorValue="126.0.42" name="Surdo Hand Stereo"/>
		<item selectorValue="126.0.41" name="Quinto Mute Stereo"/>
		<item selectorValue="127.0.3" name="Scratch L B"/>
		<item selectorValue="127.0.0" name="Scratch L"/>
	</key>
	<key value="19">
		<item selectorValue="126.0.43" name="Hand Clap 2 Stereo"/>
		<item selectorValue="126.0.42" name="Surdo Rim Stereo"/>
		<item selectorValue="126.0.41" name="Quinto Slap Open Stereo"/>
		<item selectorValue="127.0.3" name="Finger Snap B"/>
		<item selectorValue="127.0.0" name="Finger Snap"/>
	</key>
	<key value="20">
		<item selectorValue="126.0.43" name="Finger Snap Stereo"/>
		<item selectorValue="126.0.42" name="Surdo Open Stereo"/>
		<item selectorValue="126.0.41" name="Quinto Slap Stereo"/>
		<item selectorValue="127.0.3" name="Click Noise B"/>
		<item selectorValue="127.0.0" name="Click Noise"/>
	</key>
	<key value="21">
		<item selectorValue="126.0.43" name="Castanet Stereo"/>
		<item selectorValue="126.0.42" name="Surdo Mute Stereo"/>
		<item selectorValue="126.0.41" name="Quinto Slap Mute Stereo"/>
		<item selectorValue="127.0.3" name="Metronome Click B"/>
		<item selectorValue="127.0.0" name="Metronome Click"/>
	</key>
	<key value="22">
		<item selectorValue="126.0.43" name="Conga H Tip Stereo"/>
		<item selectorValue="126.0.42" name="Conga H Tip Stereo"/>
		<item selectorValue="126.0.41" name="Conga Mellow H Tip Stereo"/>
		<item selectorValue="126.0.40" name="Conga H Tip Stereo"/>
		<item selectorValue="127.0.3" name="Metronome Bell B"/>
		<item selectorValue="127.0.0" name="Metronome Bell"/>
	</key>
	<key value="23">
		<item selectorValue="126.0.43" name="Conga H Heel Stereo"/>
		<item selectorValue="126.0.42" name="Conga H Heel Stereo"/>
		<item selectorValue="126.0.41" name="Conga Mellow H Heel Stereo"/>
		<item selectorValue="126.0.40" name="Conga H Heel Stereo"/>
		<item selectorValue="127.0.3" name="Seq Click L B"/>
		<item selectorValue="127.0.0" name="Seq Click L"/>
	</key>
	<key value="24">
		<item selectorValue="126.0.43" name="Conga H Open Stereo"/>
		<item selectorValue="126.0.42" name="Conga H Open Stereo"/>
		<item selectorValue="126.0.41" name="Conga Mellow H Open Stereo"/>
		<item selectorValue="126.0.40" name="Conga H Open Stereo"/>
		<item selectorValue="127.0.3" name="Seq Click H B"/>
		<item selectorValue="127.0.0" name="Seq Click H"/>
	</key>
	<key value="25">
		<item selectorValue="127.0.31" name="Brush Tap V"/>
		<item selectorValue="127.0.30" name="Brush Tap V"/>
		<item selectorValue="127.0.29" name="Brush Tap V"/>
		<item selectorValue="127.0.28" name="Brush Tap V"/>
		<item selectorValue="127.0.26" name="Brush Tap V"/>
		<item selectorValue="127.0.85" name="Brush Tap Stereo"/>
		<item selectorValue="127.0.84" name="Brush Tap Stereo"/>
		<item selectorValue="127.0.83" name="Brush Tap Stereo"/>
		<item selectorValue="127.0.82" name="Brush Tap"/>
		<item selectorValue="127.0.17" name="Brush Tap V"/>
		<item selectorValue="127.0.81" name="Brush Tap"/>
		<item selectorValue="127.0.80" name="Brush Tap"/>
		<item selectorValue="127.0.9" name="Brush Tap V"/>
		<item selectorValue="127.0.7" name="Brush Tap V"/>
		<item selectorValue="127.0.6" name="Brush Tap V"/>
		<item selectorValue="127.0.5" name="Brush Tap V"/>
		<item selectorValue="127.0.4" name="Brush Tap V"/>
		<item selectorValue="127.0.3" name="Brush Tap B"/>
		<item selectorValue="127.0.2" name="Brush Tap V"/>
		<item selectorValue="127.0.66" name="Brush Tap V"/>
		<item selectorValue="127.0.65" name="Brush Tap V"/>
		<item selectorValue="127.0.0" name="Brush Tap"/>
		<item selectorValue="127.0.64" name="Brush Tap V"/>
		<item selectorValue="127.0.57" name="Brush Tap Natural"/>
		<item selectorValue="127.0.56" name="Brush Tap Natural"/>
		<item selectorValue="126.0.43" name="Conga H Mute Stereo"/>
		<item selectorValue="126.0.42" name="Conga H Mute Stereo"/>
		<item selectorValue="126.0.41" name="Conga Mellow H Mute Stereo"/>
		<item selectorValue="126.0.40" name="Conga H Mute Stereo"/>
		<item selectorValue="127.0.33" name="Brush Tap V"/>
	</key>
	<key value="26">
		<item selectorValue="127.0.31" name="Brush Swirl V"/>
		<item selectorValue="127.0.30" name="Brush Swirl V"/>
		<item selectorValue="127.0.29" name="Brush Swirl V"/>
		<item selectorValue="127.0.28" name="Brush Swirl V"/>
		<item selectorValue="127.0.26" name="Brush Swirl V"/>
		<item selectorValue="127.0.85" name="Brush Swirl Stereo"/>
		<item selectorValue="127.0.84" name="Brush Swirl Stereo"/>
		<item selectorValue="127.0.83" name="Brush Swirl Stereo"/>
		<item selectorValue="127.0.82" name="Brush Swirl L"/>
		<item selectorValue="127.0.17" name="Brush Swirl V"/>
		<item selectorValue="127.0.81" name="Brush Swirl L"/>
		<item selectorValue="127.0.80" name="Brush Swirl L"/>
		<item selectorValue="127.0.9" name="Brush Swirl V"/>
		<item selectorValue="127.0.7" name="Brush Swirl V"/>
		<item selectorValue="127.0.6" name="Brush Swirl V"/>
		<item selectorValue="127.0.5" name="Brush Swirl V"/>
		<item selectorValue="127.0.4" name="Brush Swirl V"/>
		<item selectorValue="127.0.3" name="Brush Swirl B"/>
		<item selectorValue="127.0.2" name="Brush Swirl V"/>
		<item selectorValue="127.0.66" name="Brush Swirl V"/>
		<item selectorValue="127.0.65" name="Brush Swirl V"/>
		<item selectorValue="127.0.0" name="Brush Swirl"/>
		<item selectorValue="127.0.64" name="Brush Swirl V"/>
		<item selectorValue="127.0.57" name="Brush Swirl Natural L"/>
		<item selectorValue="127.0.56" name="Brush Swirl Natural L"/>
		<item selectorValue="126.0.43" name="Conga H Slap Open Stereo"/>
		<item selectorValue="126.0.42" name="Conga H Slap Open Stereo"/>
		<item selectorValue="126.0.41" name="Conga Mellow H Slap Open Stereo"/>
		<item selectorValue="126.0.40" name="Conga H Slap Open Stereo"/>
		<item selectorValue="127.0.33" name="Brush Swirl V"/>
	</key>
	<key value="27">
		<item selectorValue="127.0.31" name="Brush Slap V"/>
		<item selectorValue="127.0.30" name="Brush Slap V"/>
		<item selectorValue="127.0.29" name="Brush Slap V"/>
		<item selectorValue="127.0.28" name="Brush Slap V"/>
		<item selectorValue="127.0.26" name="Brush Slap V"/>
		<item selectorValue="127.0.85" name="Brush Slap Stereo"/>
		<item selectorValue="127.0.84" name="Brush Slap Stereo"/>
		<item selectorValue="127.0.83" name="Brush Slap Stereo"/>
		<item selectorValue="127.0.82" name="Brush Slap"/>
		<item selectorValue="127.0.17" name="Brush Slap V"/>
		<item selectorValue="127.0.81" name="Brush Slap"/>
		<item selectorValue="127.0.80" name="Brush Slap"/>
		<item selectorValue="127.0.9" name="Brush Slap V"/>
		<item selectorValue="127.0.7" name="Brush Slap V"/>
		<item selectorValue="127.0.6" name="Brush Slap V"/>
		<item selectorValue="127.0.5" name="Brush Slap V"/>
		<item selectorValue="127.0.4" name="Brush Slap V"/>
		<item selectorValue="127.0.3" name="Brush Slap B"/>
		<item selectorValue="127.0.2" name="Brush Slap V"/>
		<item selectorValue="127.0.66" name="Brush Slap V"/>
		<item selectorValue="127.0.65" name="Brush Slap V"/>
		<item selectorValue="127.0.0" name="Brush Slap"/>
		<item selectorValue="127.0.64" name="Brush Slap V"/>
